window.UNIT_BANK_A1 = {
  unit: 'a1',
  unitTitle: '基础问候与自我介绍',
  basicPool: [
    // ===== 单词题 =====
    { id: 'a1_vocab_hej', kind: 'vocab_spelling', concept: 'Hej', lemma: 'Hej', source: 'vocab', prompt: { zh: '你好！' }, answer: 'Hej' },
    { id: 'a1_vocab_hej_da', kind: 'vocab_spelling', concept: 'Hej då', lemma: 'Hej då', source: 'vocab', prompt: { zh: '再见！' }, answer: 'Hej då' },
    { id: 'a1_vocab_halla', kind: 'vocab_spelling', concept: 'Hallå', lemma: 'Hallå', source: 'vocab', prompt: { zh: '喂！/你好！' }, answer: 'Hallå' },
    { id: 'a1_vocab_god_morgon', kind: 'vocab_spelling', concept: 'God morgon', lemma: 'God morgon', source: 'vocab', prompt: { zh: '早上好！' }, answer: 'God morgon' },
    { id: 'a1_vocab_god_dag', kind: 'vocab_spelling', concept: 'God dag', lemma: 'God dag', source: 'vocab', prompt: { zh: '日安！' }, answer: 'God dag' },
    { id: 'a1_vocab_god_kvall', kind: 'vocab_spelling', concept: 'God kväll', lemma: 'God kväll', source: 'vocab', prompt: { zh: '晚上好！' }, answer: 'God kväll' },
    { id: 'a1_vocab_god_natt', kind: 'vocab_spelling', concept: 'God natt', lemma: 'God natt', source: 'vocab', prompt: { zh: '晚安！' }, answer: 'God natt' },
    { id: 'a1_vocab_vi_ses', kind: 'vocab_spelling', concept: 'Vi ses', lemma: 'Vi ses', source: 'vocab', prompt: { zh: '再见！（我们再见）' }, answer: 'Vi ses' },
    { id: 'a1_vocab_ha_det_bra', kind: 'vocab_spelling', concept: 'Ha det bra', lemma: 'Ha det bra', source: 'vocab', prompt: { zh: '保重！' }, answer: 'Ha det bra' },
    { id: 'a1_vocab_heta', kind: 'vocab_spelling', concept: 'heta', lemma: 'heta', source: 'vocab', prompt: { zh: '叫做，名叫（动词原形）' }, answer: 'heta' },
    { id: 'a1_vocab_vara', kind: 'vocab_spelling', concept: 'vara', lemma: 'vara', source: 'vocab', prompt: { zh: '是（动词原形）' }, answer: 'vara' },
    { id: 'a1_vocab_heter', kind: 'vocab_spelling', concept: 'heter', lemma: 'heter', source: 'vocab', prompt: { zh: '（我/你/他）叫' }, answer: 'heter' },
    { id: 'a1_vocab_ar', kind: 'vocab_spelling', concept: 'är', lemma: 'är', source: 'vocab', prompt: { zh: '是（vara 的现在时）' }, answer: 'är' },
    { id: 'a1_vocab_fran', kind: 'vocab_spelling', concept: 'ifrån', lemma: 'ifrån', source: 'vocab', prompt: { zh: '来自，从' }, answer: 'ifrån' },
    { id: 'a1_vocab_namn', kind: 'vocab_spelling', concept: 'namn', lemma: 'namn', source: 'vocab', prompt: { zh: '名字' }, answer: 'ett namn' },
    { id: 'a1_vocab_land', kind: 'vocab_spelling', concept: 'land', lemma: 'land', source: 'vocab', prompt: { zh: '国家' }, answer: 'ett land' },
    { id: 'a1_vocab_trevligt_att_traffas', kind: 'vocab_spelling', concept: 'Trevligt att träffas', lemma: 'Trevligt att träffas', source: 'vocab', prompt: { zh: '很高兴认识你！' }, answer: 'Trevligt att träffas' },
    { id: 'a1_vocab_var_ar_du_fran', kind: 'vocab_spelling', concept: 'Var är du ifrån', lemma: 'Var är du ifrån', source: 'vocab', prompt: { zh: '你来自哪里？' }, answer: 'Var är du ifrån' },
    { id: 'a1_vocab_tack', kind: 'vocab_spelling', concept: 'Tack', lemma: 'Tack', source: 'vocab', prompt: { zh: '谢谢！' }, answer: 'Tack' },
    { id: 'a1_vocab_tack_sa_mycket', kind: 'vocab_spelling', concept: 'Tack så mycket', lemma: 'Tack så mycket', source: 'vocab', prompt: { zh: '非常感谢！' }, answer: 'Tack så mycket' },
    { id: 'a1_vocab_varsagod', kind: 'vocab_spelling', concept: 'Varsågod', lemma: 'Varsågod', source: 'vocab', prompt: { zh: '不客气！/ 请！' }, answer: 'Varsågod' },
    { id: 'a1_vocab_forlat', kind: 'vocab_spelling', concept: 'Förlåt', lemma: 'Förlåt', source: 'vocab', prompt: { zh: '对不起！' }, answer: 'Förlåt' },
    { id: 'a1_vocab_ursakta', kind: 'vocab_spelling', concept: 'Ursäkta', lemma: 'Ursäkta', source: 'vocab', prompt: { zh: '打扰一下！/ 借过！' }, answer: 'Ursäkta' },
    { id: 'a1_vocab_ja', kind: 'vocab_spelling', concept: 'Ja', lemma: 'Ja', source: 'vocab', prompt: { zh: '是' }, answer: 'Ja' },
    { id: 'a1_vocab_nej', kind: 'vocab_spelling', concept: 'Nej', lemma: 'Nej', source: 'vocab', prompt: { zh: '否，不' }, answer: 'Nej' },
    { id: 'a1_vocab_hur_mar_du', kind: 'vocab_spelling', concept: 'Hur mår du', lemma: 'Hur mår du', source: 'vocab', prompt: { zh: '你好吗？' }, answer: 'Hur mår du' },
    { id: 'a1_vocab_bra', kind: 'vocab_spelling', concept: 'Bra', lemma: 'Bra', source: 'vocab', prompt: { zh: '好的，很好' }, answer: 'Bra' },
    { id: 'a1_vocab_ett_en', kind: 'vocab_spelling', concept: 'ett / en', lemma: 'ett / en', source: 'vocab', prompt: { zh: '一（1）' }, answer: 'ett / en' },
    { id: 'a1_vocab_tva', kind: 'vocab_spelling', concept: 'två', lemma: 'två', source: 'vocab', prompt: { zh: '二（2）' }, answer: 'två' },
    { id: 'a1_vocab_tre', kind: 'vocab_spelling', concept: 'tre', lemma: 'tre', source: 'vocab', prompt: { zh: '三（3）' }, answer: 'tre' },
    { id: 'a1_vocab_fyra', kind: 'vocab_spelling', concept: 'fyra', lemma: 'fyra', source: 'vocab', prompt: { zh: '四（4）' }, answer: 'fyra' },
    { id: 'a1_vocab_fem', kind: 'vocab_spelling', concept: 'fem', lemma: 'fem', source: 'vocab', prompt: { zh: '五（5）' }, answer: 'fem' },
    { id: 'a1_vocab_sex', kind: 'vocab_spelling', concept: 'sex', lemma: 'sex', source: 'vocab', prompt: { zh: '六（6）' }, answer: 'sex' },
    { id: 'a1_vocab_sju', kind: 'vocab_spelling', concept: 'sju', lemma: 'sju', source: 'vocab', prompt: { zh: '七（7）' }, answer: 'sju' },
    { id: 'a1_vocab_atta', kind: 'vocab_spelling', concept: 'åtta', lemma: 'åtta', source: 'vocab', prompt: { zh: '八（8）' }, answer: 'åtta' },
    { id: 'a1_vocab_nio', kind: 'vocab_spelling', concept: 'nio', lemma: 'nio', source: 'vocab', prompt: { zh: '九（9）' }, answer: 'nio' },
    { id: 'a1_vocab_tio', kind: 'vocab_spelling', concept: 'tio', lemma: 'tio', source: 'vocab', prompt: { zh: '十（10）' }, answer: 'tio' },
    // ===== 固定表达题 =====
    { id: 'a1_phrase_hej', kind: 'phrase_fill', concept: 'hej', lemma: 'Hej', source: 'phrase', prompt: { zh: '你好！' }, template: '{{Hej}}!' },
    { id: 'a1_phrase_god_morgon', kind: 'phrase_fill', concept: 'god_morgon', lemma: 'God morgon', source: 'phrase', prompt: { zh: '早上好！' }, template: '{{God morgon}}!' },
    { id: 'a1_phrase_hej_da', kind: 'phrase_fill', concept: 'hej_da', lemma: 'Hej då', source: 'phrase', prompt: { zh: '再见！' }, template: '{{Hej då}}!' },
    { id: 'a1_phrase_ha_det_bra', kind: 'phrase_fill', concept: 'ha_det_bra', lemma: 'Ha det bra', source: 'phrase', prompt: { zh: '保重！' }, template: '{{Ha det bra}}!' },
    { id: 'a1_phrase_god_natt', kind: 'phrase_fill', concept: 'god_natt', lemma: 'God natt', source: 'phrase', prompt: { zh: '晚安！' }, template: '{{God natt}}!' },
    { id: 'a1_phrase_jag_heter_anna', kind: 'phrase_fill', concept: 'jag_heter_anna', lemma: 'heter', source: 'phrase', prompt: { zh: '我叫 Anna。' }, template: 'Jag {{heter}} Anna.' },
    { id: 'a1_phrase_vad_heter_du', kind: 'phrase_fill', concept: 'vad_heter_du', lemma: 'heter', source: 'phrase', prompt: { zh: '你叫什么名字？' }, template: 'Vad {{heter}} du?' },
    { id: 'a1_phrase_jag_ar_fran_kina', kind: 'phrase_fill', concept: 'jag_ar_fran_kina', lemma: 'är från', source: 'phrase', prompt: { zh: '我来自中国。' }, template: 'Jag {{är från}} Kina.' },
    { id: 'a1_phrase_jag_ar_student', kind: 'phrase_fill', concept: 'jag_ar_student', lemma: 'är', source: 'phrase', prompt: { zh: '我是学生。' }, template: 'Jag {{är}} student.' },
    { id: 'a1_phrase_han_ar_larare', kind: 'phrase_fill', concept: 'han_ar_larare', lemma: 'är', source: 'phrase', prompt: { zh: '他是老师。' }, template: 'Han {{är}} lärare.' },
    { id: 'a1_phrase_trevligt_att_traffas', kind: 'phrase_fill', concept: 'trevligt_att_traffas', lemma: 'Trevligt att träffas', source: 'phrase', prompt: { zh: '很高兴认识你！' }, template: '{{Trevligt att träffas}}!' },
    { id: 'a1_phrase_var_ar_du_fran', kind: 'phrase_fill', concept: 'var_ar_du_fran', lemma: 'Var är du ifrån', source: 'phrase', prompt: { zh: '你来自哪里？' }, template: '{{Var är du ifrån}}?' },
    { id: 'a1_phrase_tack', kind: 'phrase_fill', concept: 'tack', lemma: 'Tack', source: 'phrase', prompt: { zh: '谢谢！' }, template: '{{Tack}}!' },
    { id: 'a1_phrase_tack_sa_mycket', kind: 'phrase_fill', concept: 'tack_sa_mycket', lemma: 'Tack så mycket', source: 'phrase', prompt: { zh: '非常感谢！' }, template: '{{Tack så mycket}}!' },
    { id: 'a1_phrase_varsagod', kind: 'phrase_fill', concept: 'varsagod', lemma: 'Varsågod', source: 'phrase', prompt: { zh: '不客气！' }, template: '{{Varsågod}}!' },
    { id: 'a1_phrase_forlat', kind: 'phrase_fill', concept: 'forlat', lemma: 'Förlåt', source: 'phrase', prompt: { zh: '对不起！' }, template: '{{Förlåt}}!' },
    { id: 'a1_phrase_hur_mar_du', kind: 'phrase_fill', concept: 'hur_mar_du', lemma: 'Hur mår du', source: 'phrase', prompt: { zh: '你好吗？' }, template: '{{Hur mår du}}?' },
    { id: 'a1_phrase_bra_tack', kind: 'phrase_fill', concept: 'bra_tack', lemma: 'Bra', source: 'phrase', prompt: { zh: '很好，谢谢！' }, template: '{{Bra}}, tack!' },
    { id: 'a1_phrase_ja_nej', kind: 'phrase_fill', concept: 'ja_nej', lemma: 'Ja Nej', source: 'phrase', prompt: { zh: '是 / 否' }, template: '{{Ja}} / {{Nej}}' },
    { id: 'a1_phrase_tva_kaffe', kind: 'phrase_fill', concept: 'tva_kaffe', lemma: 'två', source: 'phrase', prompt: { zh: '两杯咖啡' }, template: '{{två}} kaffe' },
    { id: 'a1_phrase_klockan_atta', kind: 'phrase_fill', concept: 'klockan_atta', lemma: 'åtta', source: 'phrase', prompt: { zh: '八点钟' }, template: 'klockan {{åtta}}' },
    { id: 'a1_phrase_klockan_tio', kind: 'phrase_fill', concept: 'klockan_tio', lemma: 'tio', source: 'phrase', prompt: { zh: '十点钟' }, template: 'klockan {{tio}}' },
    { id: 'a1_phrase_sju_dagar', kind: 'phrase_fill', concept: 'sju_dagar', lemma: 'sju', source: 'phrase', prompt: { zh: '七天' }, template: '{{sju}} dagar' },
    // ===== 对话句题 =====
    { id: 'a1_dialog_hej_jag_heter_anna', kind: 'dialog_fill', concept: 'hej_jag_heter_anna', lemma: 'Hej heter', source: 'dialog', prompt: { zh: '你好！我叫 Anna。你叫什么名字？' }, template: '{{Hej}}! Jag {{heter}} Anna. Vad {{heter}} du?' },
    { id: 'a1_dialog_hej_jag_heter_wei', kind: 'dialog_fill', concept: 'hej_jag_heter_wei', lemma: 'Hej Trevligt att träffas', source: 'dialog', prompt: { zh: '你好！我叫 Wei。很高兴认识你！' }, template: '{{Hej}}! Jag heter Wei. {{Trevligt att träffas}}!' },
    { id: 'a1_dialog_var_ar_du_fran', kind: 'dialog_fill', concept: 'var_ar_du_fran_dialog', lemma: 'Var är du ifrån', source: 'dialog', prompt: { zh: '同样！你从哪里来？' }, template: 'Trevligt! {{Var är du ifrån}}?' },
    { id: 'a1_dialog_jag_ar_fran_kina', kind: 'dialog_fill', concept: 'jag_ar_fran_kina_dialog', lemma: 'är från', source: 'dialog', prompt: { zh: '我来自中国。你呢？' }, template: 'Jag {{är från}} Kina. Och du?' },
    { id: 'a1_dialog_jag_ar_larare_har', kind: 'dialog_fill', concept: 'jag_ar_larare_har', lemma: 'är', source: 'dialog', prompt: { zh: '我来自瑞典。我是这里的老师。' }, template: 'Jag är från Sverige. Jag {{är}} lärare här.' },
    { id: 'a1_dialog_hej_da_student', kind: 'dialog_fill', concept: 'hej_da_student', lemma: 'Hej då', source: 'dialog', prompt: { zh: '我明白了。我是学生。再见！' }, template: 'Jag förstår. Jag är student. {{Hej då}}!' },
    { id: 'a1_dialog_hej_da_ha_det_bra', kind: 'dialog_fill', concept: 'hej_da_ha_det_bra', lemma: 'Hej då Ha det bra', source: 'dialog', prompt: { zh: '再见！保重！' }, template: '{{Hej då}}! {{Ha det bra}}!' },
    { id: 'a1_dialog_god_morgon_hur_mar_du', kind: 'dialog_fill', concept: 'god_morgon_hur_mar_du', lemma: 'God morgon', source: 'dialog', prompt: { zh: '早上好！你好吗？' }, template: '{{God morgon}}! Hur mår du?' },
    { id: 'a1_dialog_god_morgon_bra_tack', kind: 'dialog_fill', concept: 'god_morgon_bra_tack', lemma: 'God morgon tack', source: 'dialog', prompt: { zh: '早上好！很好，谢谢！你呢？' }, template: '{{God morgon}}! Bra, {{tack}}! Och du?' },
    { id: 'a1_dialog_tva_kaffe_varsagod', kind: 'dialog_fill', concept: 'tva_kaffe_varsagod', lemma: 'två varsågod', source: 'dialog', prompt: { zh: '也很好，谢谢！这是两杯咖啡，给你。' }, template: 'Också bra, tack! Det är {{två}} kaffe, {{varsågod}}.' },
    { id: 'a1_dialog_tack_sa_mycket', kind: 'dialog_fill', concept: 'tack_sa_mycket_dialog', lemma: 'Tack så mycket', source: 'dialog', prompt: { zh: '非常感谢！' }, template: '{{Tack så mycket}}!' },
    { id: 'a1_dialog_varsagod_ha_det_bra', kind: 'dialog_fill', concept: 'varsagod_ha_det_bra', lemma: 'Varsågod Ha det bra', source: 'dialog', prompt: { zh: '不客气！保重！' }, template: '{{Varsågod}}! {{Ha det bra}}!' },
    { id: 'a1_dialog_halla', kind: 'dialog_fill', concept: 'halla', lemma: 'Hallå', source: 'dialog', prompt: { zh: '喂？' }, template: '{{Hallå}}?' },
    { id: 'a1_dialog_hej_det_ar_anna', kind: 'dialog_fill', concept: 'hej_det_ar_anna', lemma: 'Hej', source: 'dialog', prompt: { zh: '你好！我是 Anna。你好吗？' }, template: '{{Hej}}! Det är Anna. Hur mår du?' },
    { id: 'a1_dialog_bra_tack_vad_heter_du', kind: 'dialog_fill', concept: 'bra_tack_vad_heter_du', lemma: 'tack', source: 'dialog', prompt: { zh: '很好，谢谢！你的瑞典语名字叫什么？' }, template: 'Bra, {{tack}}! Vad heter du på svenska?' },
    { id: 'a1_dialog_jag_heter_anna_larsson', kind: 'dialog_fill', concept: 'jag_heter_anna_larsson', lemma: 'heter Förlåt', source: 'dialog', prompt: { zh: '我叫 Anna Larsson。对不起，我现在必须走了。' }, template: 'Jag {{heter}} Anna Larsson. {{Förlåt}}, jag måste gå nu.' },
    { id: 'a1_dialog_vi_ses_hej_da', kind: 'dialog_fill', concept: 'vi_ses_hej_da', lemma: 'Vi ses Hej då', source: 'dialog', prompt: { zh: '好的！再见！拜拜！' }, template: 'Okej! {{Vi ses}}! {{Hej då}}!' }
  ],
  advancedPool: [
    // ===== verb_forms =====
    { id: 'a1_verb_heta_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'heta', prompt: { zh: '叫做，名叫' }, template: '{{heta}} | {{heter}} | {{hette}} | {{hetat}}' },
    { id: 'a1_verb_vara_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'vara', prompt: { zh: '是' }, template: '{{vara}} | {{är}} | {{var}} | {{varit}}' },
    // ===== noun_forms =====
    { id: 'a1_noun_namn_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'namn', prompt: { zh: '名字' }, template: '{{ett}} | {{namn}} | {{namnet}} | {{namn}} | {{namnen}}' },
    { id: 'a1_noun_land_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'land', prompt: { zh: '国家' }, template: '{{ett}} | {{land}} | {{landet}} | {{länder}} | {{länderna}}' },
    // ===== comparison_forms =====
    { id: 'a1_comp_bra_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'bra', prompt: { zh: '好的' }, template: '{{bra}} | {{bättre}} | {{bäst}}' }
  ]
};
