window.UNIT_BANK_A2 = {
  unit: 'a2',
  unitTitle: '数字、时间、日期',
  basicPool: [
    // ===== 单词题 =====
    { id: 'a2_vocab_elva', kind: 'vocab_spelling', concept: 'elva', lemma: 'elva', source: 'vocab', prompt: { zh: '十一（11）' }, answer: 'elva' },
    { id: 'a2_vocab_tolv', kind: 'vocab_spelling', concept: 'tolv', lemma: 'tolv', source: 'vocab', prompt: { zh: '十二（12）' }, answer: 'tolv' },
    { id: 'a2_vocab_tretton', kind: 'vocab_spelling', concept: 'tretton', lemma: 'tretton', source: 'vocab', prompt: { zh: '十三（13）' }, answer: 'tretton' },
    { id: 'a2_vocab_fjorton', kind: 'vocab_spelling', concept: 'fjorton', lemma: 'fjorton', source: 'vocab', prompt: { zh: '十四（14）' }, answer: 'fjorton' },
    { id: 'a2_vocab_femton', kind: 'vocab_spelling', concept: 'femton', lemma: 'femton', source: 'vocab', prompt: { zh: '十五（15）' }, answer: 'femton' },
    { id: 'a2_vocab_tjugo', kind: 'vocab_spelling', concept: 'tjugo', lemma: 'tjugo', source: 'vocab', prompt: { zh: '二十（20）' }, answer: 'tjugo' },
    { id: 'a2_vocab_trettio', kind: 'vocab_spelling', concept: 'trettio', lemma: 'trettio', source: 'vocab', prompt: { zh: '三十（30）' }, answer: 'trettio' },
    { id: 'a2_vocab_femtio', kind: 'vocab_spelling', concept: 'femtio', lemma: 'femtio', source: 'vocab', prompt: { zh: '五十（50）' }, answer: 'femtio' },
    { id: 'a2_vocab_hundra', kind: 'vocab_spelling', concept: 'hundra', lemma: 'hundra', source: 'vocab', prompt: { zh: '一百（100）' }, answer: 'hundra' },
    { id: 'a2_vocab_tjugofem', kind: 'vocab_spelling', concept: 'tjugofem', lemma: 'tjugofem', source: 'vocab', prompt: { zh: '二十五（25）' }, answer: 'tjugofem' },
    { id: 'a2_vocab_klockan', kind: 'vocab_spelling', concept: 'klockan', lemma: 'klockan', source: 'vocab', prompt: { zh: '时钟；几点' }, answer: 'klockan' },
    { id: 'a2_vocab_timme', kind: 'vocab_spelling', concept: 'timme', lemma: 'timme', source: 'vocab', prompt: { zh: '小时' }, answer: 'timme' },
    { id: 'a2_vocab_minut', kind: 'vocab_spelling', concept: 'minut', lemma: 'minut', source: 'vocab', prompt: { zh: '分钟' }, answer: 'minut' },
    { id: 'a2_vocab_kvart', kind: 'vocab_spelling', concept: 'kvart', lemma: 'kvart', source: 'vocab', prompt: { zh: '一刻钟' }, answer: 'kvart' },
    { id: 'a2_vocab_halv', kind: 'vocab_spelling', concept: 'halv', lemma: 'halv', source: 'vocab', prompt: { zh: '半（下一小时的半点）' }, answer: 'halv' },
    { id: 'a2_vocab_morgon', kind: 'vocab_spelling', concept: 'morgon', lemma: 'morgon', source: 'vocab', prompt: { zh: '早晨' }, answer: 'morgon' },
    { id: 'a2_vocab_formiddag', kind: 'vocab_spelling', concept: 'förmiddag', lemma: 'förmiddag', source: 'vocab', prompt: { zh: '上午' }, answer: 'förmiddag' },
    { id: 'a2_vocab_eftermiddag', kind: 'vocab_spelling', concept: 'eftermiddag', lemma: 'eftermiddag', source: 'vocab', prompt: { zh: '下午' }, answer: 'eftermiddag' },
    { id: 'a2_vocab_kvall', kind: 'vocab_spelling', concept: 'kväll', lemma: 'kväll', source: 'vocab', prompt: { zh: '晚上' }, answer: 'kväll' },
    { id: 'a2_vocab_mandag', kind: 'vocab_spelling', concept: 'måndag', lemma: 'måndag', source: 'vocab', prompt: { zh: '周一' }, answer: 'måndag' },
    { id: 'a2_vocab_tisdag', kind: 'vocab_spelling', concept: 'tisdag', lemma: 'tisdag', source: 'vocab', prompt: { zh: '周二' }, answer: 'tisdag' },
    { id: 'a2_vocab_onsdag', kind: 'vocab_spelling', concept: 'onsdag', lemma: 'onsdag', source: 'vocab', prompt: { zh: '周三' }, answer: 'onsdag' },
    { id: 'a2_vocab_torsdag', kind: 'vocab_spelling', concept: 'torsdag', lemma: 'torsdag', source: 'vocab', prompt: { zh: '周四' }, answer: 'torsdag' },
    { id: 'a2_vocab_fredag', kind: 'vocab_spelling', concept: 'fredag', lemma: 'fredag', source: 'vocab', prompt: { zh: '周五' }, answer: 'fredag' },
    { id: 'a2_vocab_lordag', kind: 'vocab_spelling', concept: 'lördag', lemma: 'lördag', source: 'vocab', prompt: { zh: '周六' }, answer: 'lördag' },
    { id: 'a2_vocab_sondag', kind: 'vocab_spelling', concept: 'söndag', lemma: 'söndag', source: 'vocab', prompt: { zh: '周日' }, answer: 'söndag' },
    { id: 'a2_vocab_januari', kind: 'vocab_spelling', concept: 'januari', lemma: 'januari', source: 'vocab', prompt: { zh: '一月' }, answer: 'januari' },
    { id: 'a2_vocab_februari', kind: 'vocab_spelling', concept: 'februari', lemma: 'februari', source: 'vocab', prompt: { zh: '二月' }, answer: 'februari' },
    { id: 'a2_vocab_mars', kind: 'vocab_spelling', concept: 'mars', lemma: 'mars', source: 'vocab', prompt: { zh: '三月' }, answer: 'mars' },
    { id: 'a2_vocab_april', kind: 'vocab_spelling', concept: 'april', lemma: 'april', source: 'vocab', prompt: { zh: '四月' }, answer: 'april' },
    { id: 'a2_vocab_maj', kind: 'vocab_spelling', concept: 'maj', lemma: 'maj', source: 'vocab', prompt: { zh: '五月' }, answer: 'maj' },
    { id: 'a2_vocab_juni', kind: 'vocab_spelling', concept: 'juni', lemma: 'juni', source: 'vocab', prompt: { zh: '六月' }, answer: 'juni' },
    { id: 'a2_vocab_juli', kind: 'vocab_spelling', concept: 'juli', lemma: 'juli', source: 'vocab', prompt: { zh: '七月' }, answer: 'juli' },
    { id: 'a2_vocab_augusti', kind: 'vocab_spelling', concept: 'augusti', lemma: 'augusti', source: 'vocab', prompt: { zh: '八月' }, answer: 'augusti' },
    { id: 'a2_vocab_september', kind: 'vocab_spelling', concept: 'september', lemma: 'september', source: 'vocab', prompt: { zh: '九月' }, answer: 'september' },
    { id: 'a2_vocab_oktober', kind: 'vocab_spelling', concept: 'oktober', lemma: 'oktober', source: 'vocab', prompt: { zh: '十月' }, answer: 'oktober' },
    { id: 'a2_vocab_november', kind: 'vocab_spelling', concept: 'november', lemma: 'november', source: 'vocab', prompt: { zh: '十一月' }, answer: 'november' },
    { id: 'a2_vocab_december', kind: 'vocab_spelling', concept: 'december', lemma: 'december', source: 'vocab', prompt: { zh: '十二月' }, answer: 'december' },
    // ===== 固定表达题 =====
    { id: 'a2_phrase_tjugofem_elever', kind: 'phrase_fill', concept: 'tjugofem_elever', lemma: 'tjugofem', source: 'phrase', prompt: { zh: '二十五个学生' }, template: '{{tjugofem}} elever' },
    { id: 'a2_phrase_klockan_tolv', kind: 'phrase_fill', concept: 'klockan_tolv', lemma: 'tolv', source: 'phrase', prompt: { zh: '十二点钟' }, template: 'klockan {{tolv}}' },
    { id: 'a2_phrase_femtio_kronor', kind: 'phrase_fill', concept: 'femtio_kronor', lemma: 'femtio', source: 'phrase', prompt: { zh: '五十克朗' }, template: '{{femtio}} kronor' },
    { id: 'a2_phrase_hundra_kronor', kind: 'phrase_fill', concept: 'hundra_kronor', lemma: 'hundra', source: 'phrase', prompt: { zh: '一百克朗' }, template: '{{hundra}} kronor' },
    { id: 'a2_phrase_vad_ar_klockan', kind: 'phrase_fill', concept: 'vad_ar_klockan', lemma: 'klockan', source: 'phrase', prompt: { zh: '现在几点？' }, template: 'Vad är {{klockan}}?' },
    { id: 'a2_phrase_klockan_ar_tre', kind: 'phrase_fill', concept: 'klockan_ar_tre', lemma: 'tre', source: 'phrase', prompt: { zh: '现在是三点。' }, template: 'Klockan är {{tre}}.' },
    { id: 'a2_phrase_kvart_over_tre', kind: 'phrase_fill', concept: 'kvart_over_tre', lemma: 'Kvart över', source: 'phrase', prompt: { zh: '三点一刻。' }, template: '{{Kvart över}} tre.' },
    { id: 'a2_phrase_halv_fyra', kind: 'phrase_fill', concept: 'halv_fyra', lemma: 'Halv fyra', source: 'phrase', prompt: { zh: '三点半。' }, template: '{{Halv fyra}}.' },
    { id: 'a2_phrase_kvart_i_fyra', kind: 'phrase_fill', concept: 'kvart_i_fyra', lemma: 'Kvart i fyra', source: 'phrase', prompt: { zh: '差一刻四点。' }, template: '{{Kvart i fyra}}.' },
    { id: 'a2_phrase_klockan_tio', kind: 'phrase_fill', concept: 'klockan_tio', lemma: 'tio', source: 'phrase', prompt: { zh: '十点整。' }, template: 'klockan {{tio}}' },
    { id: 'a2_phrase_vi_ses_pa_tisdag', kind: 'phrase_fill', concept: 'vi_ses_pa_tisdag', lemma: 'tisdag', source: 'phrase', prompt: { zh: '我们周二见。' }, template: 'Vi ses på {{tisdag}}.' },
    { id: 'a2_phrase_motet_ar_pa_mandag', kind: 'phrase_fill', concept: 'motet_ar_pa_mandag', lemma: 'måndag', source: 'phrase', prompt: { zh: '会议在周一。' }, template: 'Mötet är på {{måndag}}.' },
    { id: 'a2_phrase_i_januari', kind: 'phrase_fill', concept: 'i_januari', lemma: 'januari', source: 'phrase', prompt: { zh: '在一月' }, template: 'i {{januari}}' },
    { id: 'a2_phrase_i_mars', kind: 'phrase_fill', concept: 'i_mars', lemma: 'mars', source: 'phrase', prompt: { zh: '在三月' }, template: 'i {{mars}}' },
    { id: 'a2_phrase_i_december', kind: 'phrase_fill', concept: 'i_december', lemma: 'december', source: 'phrase', prompt: { zh: '在十二月' }, template: 'i {{december}}' },
    // ===== 对话句题 =====
    { id: 'a2_dialog_vad_ar_klockan', kind: 'dialog_fill', concept: 'vad_ar_klockan_dialog', lemma: 'är klockan', source: 'dialog', prompt: { zh: '打扰一下！现在几点？' }, template: 'Ursäkta! Vad {{är}} {{klockan}}?' },
    { id: 'a2_dialog_klockan_ar_kvart_i_nio', kind: 'dialog_fill', concept: 'klockan_ar_kvart_i_nio', lemma: 'kvart i', source: 'dialog', prompt: { zh: '现在差一刻九点。' }, template: 'Klockan är {{kvart}} {{i}} nio.' },
    { id: 'a2_dialog_nasta_buss_gar_klockan_nio', kind: 'dialog_fill', concept: 'nasta_buss_gar_klockan_nio', lemma: 'Nästa går', source: 'dialog', prompt: { zh: '谢谢！下一班公交九点发车，对吗？' }, template: 'Tack! {{Nästa}} buss {{går}} klockan nio, eller?' },
    { id: 'a2_dialog_halv_tio', kind: 'dialog_fill', concept: 'halv_tio', lemma: 'halv tio', source: 'dialog', prompt: { zh: '是的，九点，然后九点半。' }, template: 'Ja, klockan nio och sedan {{halv}} {{tio}}.' },
    { id: 'a2_dialog_jag_vill_boka_en_tid', kind: 'dialog_fill', concept: 'jag_vill_boka_en_tid', lemma: 'boka tid', source: 'dialog', prompt: { zh: '我想预约一个时间，谢谢。' }, template: 'Hej! Jag vill {{boka}} en {{tid}}, tack.' },
    { id: 'a2_dialog_vilken_dag_passar_dig', kind: 'dialog_fill', concept: 'vilken_dag_passar_dig', lemma: 'Vilken dag passar', source: 'dialog', prompt: { zh: '哪一天适合你？' }, template: '{{Vilken}} {{dag}} {{passar}} dig?' },
    { id: 'a2_dialog_ar_tisdag_bra', kind: 'dialog_fill', concept: 'ar_tisdag_bra', lemma: 'tisdag', source: 'dialog', prompt: { zh: '周二可以吗？' }, template: 'Är {{tisdag}} bra?' },
    { id: 'a2_dialog_tisdag_den_femtonde_mars_klockan_tio', kind: 'dialog_fill', concept: 'tisdag_den_femtonde_mars_klockan_tio', lemma: 'tisdag femtonde tio', source: 'dialog', prompt: { zh: '好的！我们有一个时间是三月十五日周二，上午十点。' }, template: 'Ja! Vi har en tid {{tisdag}} den {{femtonde}} mars, klockan {{tio}}.' }
  ],
  advancedPool: [
    // ===== time_pattern =====
    { id: 'a2_time_klockan_tre', kind: 'morphology', source: 'pattern', lemma: 'klockan tre', prompt: { zh: '三点。' }, template: '{{klockan}} {{tre}}' },
    { id: 'a2_time_kvart_over_tre', kind: 'morphology', source: 'pattern', lemma: 'kvart över tre', prompt: { zh: '三点一刻。' }, template: '{{kvart}} {{över}} {{tre}}' },
    { id: 'a2_time_halv_fyra', kind: 'morphology', source: 'pattern', lemma: 'halv fyra', prompt: { zh: '三点半。' }, template: '{{halv}} {{fyra}}' },
    { id: 'a2_time_kvart_i_fyra', kind: 'morphology', source: 'pattern', lemma: 'kvart i fyra', prompt: { zh: '差一刻四点。' }, template: '{{kvart}} {{i}} {{fyra}}' },
    { id: 'a2_time_klockan_tio', kind: 'morphology', source: 'pattern', lemma: 'klockan tio', prompt: { zh: '十点。' }, template: '{{klockan}} {{tio}}' },
    // ===== noun_forms =====
    { id: 'a2_noun_timme_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'timme', prompt: { zh: '小时' }, template: '{{en}} | {{timme}} | {{timmen}} | {{timmar}} | {{timmarna}}' },
    { id: 'a2_noun_minut_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'minut', prompt: { zh: '分钟' }, template: '{{en}} | {{minut}} | {{minuten}} | {{minuter}} | {{minuterna}}' },
    { id: 'a2_noun_dag_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'dag', prompt: { zh: '天 / 日' }, template: '{{en}} | {{dag}} | {{dagen}} | {{dagar}} | {{dagarna}}' },
    { id: 'a2_noun_manad_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'månad', prompt: { zh: '月' }, template: '{{en}} | {{månad}} | {{månaden}} | {{månader}} | {{månaderna}}' }
  ]
};
