window.UNIT_BANK_B2 = {
  unit: 'b2',
  unitTitle: '动词现在时变位',
  basicPool: [
    // ===== 单词题 =====
    { id: 'b2_vocab_studera', kind: 'morphology', source: 'vocab', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时'], lemma: 'studera', prompt: { zh: '学习' }, template: '{{studera}} · {{studerar}}' },
    { id: 'b2_vocab_fraga', kind: 'morphology', source: 'vocab', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时'], lemma: 'fråga', prompt: { zh: '问' }, template: '{{fråga}} · {{frågar}}' },
    { id: 'b2_vocab_prata', kind: 'morphology', source: 'vocab', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时'], lemma: 'prata', prompt: { zh: '说话（口语）' }, template: '{{prata}} · {{pratar}}' },
    { id: 'b2_vocab_jobba', kind: 'morphology', source: 'vocab', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时'], lemma: 'jobba', prompt: { zh: '工作（口语）' }, template: '{{jobba}} · {{jobbar}}' },
    { id: 'b2_vocab_hitta', kind: 'morphology', source: 'vocab', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时'], lemma: 'hitta', prompt: { zh: '找到' }, template: '{{hitta}} · {{hittar}}' },
    { id: 'b2_vocab_komma', kind: 'morphology', source: 'vocab', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时'], lemma: 'komma', prompt: { zh: '来' }, template: '{{komma}} · {{kommer}}' },
    { id: 'b2_vocab_stanga', kind: 'morphology', source: 'vocab', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时'], lemma: 'stänga', prompt: { zh: '关闭' }, template: '{{stänga}} · {{stänger}}' },
    { id: 'b2_vocab_ringa', kind: 'morphology', source: 'vocab', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时'], lemma: 'ringa', prompt: { zh: '打电话' }, template: '{{ringa}} · {{ringer}}' },
    { id: 'b2_vocab_lagga', kind: 'morphology', source: 'vocab', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时'], lemma: 'lägga', prompt: { zh: '放下 / 放置' }, template: '{{lägga}} · {{lägger}}' },
    { id: 'b2_vocab_sy', kind: 'morphology', source: 'vocab', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时'], lemma: 'sy', prompt: { zh: '缝纫' }, template: '{{sy}} · {{syr}}' },
    { id: 'b2_vocab_se', kind: 'morphology', source: 'vocab', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时'], lemma: 'se', prompt: { zh: '看见' }, template: '{{se}} · {{ser}}' },
    { id: 'b2_vocab_fa', kind: 'morphology', source: 'vocab', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时'], lemma: 'få', prompt: { zh: '得到 / 可以' }, template: '{{få}} · {{får}}' },
    { id: 'b2_vocab_saga', kind: 'morphology', source: 'vocab', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时'], lemma: 'säga', prompt: { zh: '说' }, template: '{{säga}} · {{säger}}' },
    // ===== 固定表达题 =====
    { id: 'b2_phrase_laser_svenska', kind: 'phrase_fill', concept: 'hon_läser_svenska', lemma: 'läser', source: 'phrase', prompt: { zh: '她晚上读瑞典语。' }, template: 'Hon {{läser}} svenska på kvällen.' },
    { id: 'b2_phrase_kan_inte_svenska', kind: 'phrase_fill', concept: 'jag_kan_inte_svenska', lemma: 'kan', source: 'phrase', prompt: { zh: '我还不会说瑞典语。' }, template: 'Jag {{kan}} inte svenska ännu.' },
    { id: 'b2_phrase_kor_bil', kind: 'phrase_fill', concept: 'han_kör_bil', lemma: 'kör', source: 'phrase', prompt: { zh: '他开车去上班。' }, template: 'Han {{kör}} bil till arbetet.' },
    { id: 'b2_phrase_var_bor_ni', kind: 'phrase_fill', concept: 'var_bor_ni', lemma: 'bor', source: 'phrase', prompt: { zh: '你们住在哪里？' }, template: 'Var {{bor}} ni?' },
    // ===== 对话句题 =====
    { id: 'b2_dialog_vad_heter_du', kind: 'dialog_fill', concept: 'vad_heter_du', lemma: 'heter', source: 'dialog', prompt: { zh: '你叫什么名字？' }, template: 'Vad {{heter}} du?' },
    { id: 'b2_dialog_jag_heter_wei', kind: 'dialog_fill', concept: 'jag_heter_wei', lemma: 'heter', source: 'dialog', prompt: { zh: '我叫 Wei。' }, template: 'Jag {{heter}} Wei.' },
    { id: 'b2_dialog_jag_kommer_fran_kina', kind: 'dialog_fill', concept: 'jag_kommer_fran_kina', lemma: 'kommer', source: 'dialog', prompt: { zh: '我来自中国。' }, template: 'Jag {{kommer}} från Kina.' },
    { id: 'b2_dialog_jag_bor_i_stockholm', kind: 'dialog_fill', concept: 'jag_bor_i_stockholm', lemma: 'bor', source: 'dialog', prompt: { zh: '我现在住在斯德哥尔摩。' }, template: 'Jag {{bor}} nu i Stockholm.' },
    { id: 'b2_dialog_vad_arbetar_du_med', kind: 'dialog_fill', concept: 'vad_arbetar_du_med', lemma: 'arbetar', source: 'dialog', prompt: { zh: '你是做什么工作的？' }, template: 'Vad {{arbetar}} du med?' },
    { id: 'b2_dialog_jag_studerar_svenska', kind: 'dialog_fill', concept: 'jag_studerar_svenska', lemma: 'studerar', source: 'dialog', prompt: { zh: '我现在学瑞典语。' }, template: 'Jag {{studerar}} svenska nu.' },
    { id: 'b2_dialog_talar_du_annat_sprak', kind: 'dialog_fill', concept: 'talar_du_nagot_annat_sprak', lemma: 'talar', source: 'dialog', prompt: { zh: '你还会说其他语言吗？' }, template: '{{Talar}} du något annat språk?' },
    { id: 'b2_dialog_jag_forstar_inte', kind: 'dialog_fill', concept: 'jag_forstar_inte_sa_mycket', lemma: 'förstår', source: 'dialog', prompt: { zh: '我还不太懂瑞典语。' }, template: 'Jag {{förstår}} inte så mycket svenska än.' },
    { id: 'b2_dialog_jag_lar_mig_varje_dag', kind: 'dialog_fill', concept: 'jag_lar_mig_varje_dag', lemma: 'lär', source: 'dialog', prompt: { zh: '但我每天都在学。' }, template: 'Jag {{lär}} mig varje dag.' },
    { id: 'b2_dialog_vad_gor_du_pa_morgonen', kind: 'dialog_fill', concept: 'vad_gor_du_pa_morgonen', lemma: 'gör', source: 'dialog', prompt: { zh: '你早上做什么？' }, template: 'Vad {{gör}} du på morgonen?' },
    { id: 'b2_dialog_jag_gar_upp_klockan_sex', kind: 'dialog_fill', concept: 'jag_gar_upp_klockan_sex', lemma: 'går', source: 'dialog', prompt: { zh: '我六点起床。' }, template: 'Jag {{går}} upp klockan sex.' },
    { id: 'b2_dialog_sedan_tar_jag_bussen', kind: 'dialog_fill', concept: 'sedan_tar_jag_bussen', lemma: 'tar', source: 'dialog', prompt: { zh: '然后我坐公交去学校。' }, template: 'Sedan {{tar}} jag bussen till skolan.' },
    { id: 'b2_dialog_handlar_du_mat_varje_dag', kind: 'dialog_fill', concept: 'handlar_du_mat_varje_dag', lemma: 'handlar', source: 'dialog', prompt: { zh: '你每天买菜吗？' }, template: '{{Handlar}} du mat varje dag?' },
    { id: 'b2_dialog_jag_handlar_tva_ganger_i_veckan', kind: 'dialog_fill', concept: 'jag_handlar_tva_ganger_i_veckan', lemma: 'handlar', source: 'dialog', prompt: { zh: '我一周买两次。' }, template: 'Jag {{handlar}} två gånger i veckan.' },
    { id: 'b2_dialog_jag_koper_mat_pa_ica', kind: 'dialog_fill', concept: 'jag_koper_mat_pa_ica', lemma: 'köper', source: 'dialog', prompt: { zh: '我通常在 ICA 买食物。' }, template: 'Jag {{köper}} oftast mat på ICA.' },
    { id: 'b2_dialog_vet_du_om_det_finns', kind: 'dialog_fill', concept: 'vet_du_om_det_finns', lemma: 'vet finns', source: 'dialog', prompt: { zh: '你知道这里有没有好餐厅吗？' }, template: '{{Vet}} du om det {{finns}} en bra restaurang här?' },
    { id: 'b2_dialog_jag_tror_att_de_lagar', kind: 'dialog_fill', concept: 'jag_tror_att_de_lagar', lemma: 'tror lagar', source: 'dialog', prompt: { zh: '我觉得他们做的菜很好。' }, template: 'Jag {{tror}} att de {{lagar}} mycket god mat.' }
  ],
  advancedPool: [
    // ===== 动词变形 =====
    { id: 'b2_verb_arbeta_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'arbeta', prompt: { zh: '工作' }, template: '{{arbeta}} · {{arbetar}} · {{arbetade}} · {{arbetat}}' },
    { id: 'b2_verb_tala_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'tala', prompt: { zh: '说话 / 讲' }, template: '{{tala}} · {{talar}} · {{talade}} · {{talat}}' },
    { id: 'b2_verb_studera_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'studera', prompt: { zh: '学习' }, template: '{{studera}} · {{studerar}} · {{studerade}} · {{studerat}}' },
    { id: 'b2_verb_handla_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'handla', prompt: { zh: '购物' }, template: '{{handla}} · {{handlar}} · {{handlade}} · {{handlat}}' },
    { id: 'b2_verb_fraga_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'fråga', prompt: { zh: '问' }, template: '{{fråga}} · {{frågar}} · {{frågade}} · {{frågat}}' },
    { id: 'b2_verb_prata_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'prata', prompt: { zh: '说话（口语）' }, template: '{{prata}} · {{pratar}} · {{pratade}} · {{pratat}}' },
    { id: 'b2_verb_jobba_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'jobba', prompt: { zh: '工作（口语）' }, template: '{{jobba}} · {{jobbar}} · {{jobbade}} · {{jobbat}}' },
    { id: 'b2_verb_hitta_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'hitta', prompt: { zh: '找到' }, template: '{{hitta}} · {{hittar}} · {{hittade}} · {{hittat}}' },
    { id: 'b2_verb_heta_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'heta', prompt: { zh: '名叫' }, template: '{{heta}} · {{heter}} · {{hette}} · {{hetat}}' },
    { id: 'b2_verb_komma_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'komma', prompt: { zh: '来' }, template: '{{komma}} · {{kommer}} · {{kom}} · {{kommit}}' },
    { id: 'b2_verb_lasa_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'läsa', prompt: { zh: '读' }, template: '{{läsa}} · {{läser}} · {{läste}} · {{läst}}' },
    { id: 'b2_verb_stanga_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'stänga', prompt: { zh: '关闭' }, template: '{{stänga}} · {{stänger}} · {{stängde}} · {{stängt}}' },
    { id: 'b2_verb_forsta_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'förstå', prompt: { zh: '理解' }, template: '{{förstå}} · {{förstår}} · {{förstod}} · {{förstått}}' },
    { id: 'b2_verb_kora_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'köra', prompt: { zh: '开车' }, template: '{{köra}} · {{kör}} · {{körde}} · {{kört}}' },
    { id: 'b2_verb_ringa_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'ringa', prompt: { zh: '打电话' }, template: '{{ringa}} · {{ringer}} · {{ringde}} · {{ringt}}' },
    { id: 'b2_verb_lagga_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'lägga', prompt: { zh: '放下 / 放置' }, template: '{{lägga}} · {{lägger}} · {{lade}} · {{lagt}}' },
    { id: 'b2_verb_bo_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'bo', prompt: { zh: '住' }, template: '{{bo}} · {{bor}} · {{bodde}} · {{bott}}' },
    { id: 'b2_verb_ga_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'gå', prompt: { zh: '走 / 去' }, template: '{{gå}} · {{går}} · {{gick}} · {{gått}}' },
    { id: 'b2_verb_ta_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'ta', prompt: { zh: '拿 / 乘坐' }, template: '{{ta}} · {{tar}} · {{tog}} · {{tagit}}' },
    { id: 'b2_verb_tro_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'tro', prompt: { zh: '认为 / 相信' }, template: '{{tro}} · {{tror}} · {{trodde}} · {{trott}}' },
    { id: 'b2_verb_sy_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'sy', prompt: { zh: '缝纫' }, template: '{{sy}} · {{syr}} · {{sydde}} · {{sytt}}' },
    { id: 'b2_verb_vara_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'vara', prompt: { zh: '是' }, template: '{{vara}} · {{är}} · {{var}} · {{varit}}' },
    { id: 'b2_verb_ha_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'ha', prompt: { zh: '有' }, template: '{{ha}} · {{har}} · {{hade}} · {{haft}}' },
    { id: 'b2_verb_se_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'se', prompt: { zh: '看见' }, template: '{{se}} · {{ser}} · {{såg}} · {{sett}}' },
    { id: 'b2_verb_veta_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'veta', prompt: { zh: '知道' }, template: '{{veta}} · {{vet}} · {{visste}} · {{vetat}}' },
    { id: 'b2_verb_vilja_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'vilja', prompt: { zh: '想要' }, template: '{{vilja}} · {{vill}} · {{ville}} · {{velat}}' },
    { id: 'b2_verb_kunna_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'kunna', prompt: { zh: '能 / 会' }, template: '{{kunna}} · {{kan}} · {{kunde}} · {{kunnat}}' },
    { id: 'b2_verb_fa_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'få', prompt: { zh: '得到 / 可以' }, template: '{{få}} · {{får}} · {{fick}} · {{fått}}' },
    { id: 'b2_verb_saga_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'säga', prompt: { zh: '说' }, template: '{{säga}} · {{säger}} · {{sa}} · {{sagt}}' },
    { id: 'b2_verb_gora_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'göra', prompt: { zh: '做' }, template: '{{göra}} · {{gör}} · {{gjorde}} · {{gjort}}' },
    { id: 'b2_verb_finnas_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'finnas', prompt: { zh: '存在 / 有' }, template: '{{finnas}} · {{finns}} · {{fanns}} · {{funnits}}' }
  ]
};
