window.UNIT_BANK_B3 = {
  unit: 'b3',
  unitTitle: '名词复数变化',
  basicPool: [
    // ===== 单词题 =====
    { id: 'b3_vocab_hus', kind: 'vocab_spelling', concept: 'hus', lemma: 'hus', source: 'vocab', prompt: { zh: '房子（名词，单数）' }, answer: 'ett hus' },
    { id: 'b3_vocab_rum', kind: 'vocab_spelling', concept: 'rum', lemma: 'rum', source: 'vocab', prompt: { zh: '房间（名词，单数）' }, answer: 'ett rum' },
    { id: 'b3_vocab_fonster', kind: 'vocab_spelling', concept: 'fönster', lemma: 'fönster', source: 'vocab', prompt: { zh: '窗户（名词，单数）' }, answer: 'ett fönster' },
    { id: 'b3_vocab_mobel', kind: 'vocab_spelling', concept: 'möbel', lemma: 'möbel', source: 'vocab', prompt: { zh: '家具（名词，单数）' }, answer: 'en möbel' },
    { id: 'b3_vocab_stol', kind: 'vocab_spelling', concept: 'stol', lemma: 'stol', source: 'vocab', prompt: { zh: '椅子（名词，单数）' }, answer: 'en stol' },
    { id: 'b3_vocab_bord', kind: 'vocab_spelling', concept: 'bord', lemma: 'bord', source: 'vocab', prompt: { zh: '桌子（名词，单数）' }, answer: 'ett bord' },
    { id: 'b3_vocab_cykel', kind: 'vocab_spelling', concept: 'cykel', lemma: 'cykel', source: 'vocab', prompt: { zh: '自行车（名词，单数）' }, answer: 'en cykel' },
    { id: 'b3_vocab_barn', kind: 'vocab_spelling', concept: 'barn', lemma: 'barn', source: 'vocab', prompt: { zh: '孩子（名词，单数）' }, answer: 'ett barn' },
    { id: 'b3_vocab_familj', kind: 'vocab_spelling', concept: 'familj', lemma: 'familj', source: 'vocab', prompt: { zh: '家庭（名词，单数）' }, answer: 'en familj' },
    { id: 'b3_vocab_elev', kind: 'vocab_spelling', concept: 'elev', lemma: 'elev', source: 'vocab', prompt: { zh: '学生（名词，单数）' }, answer: 'en elev' },
    { id: 'b3_vocab_bok', kind: 'vocab_spelling', concept: 'bok', lemma: 'bok', source: 'vocab', prompt: { zh: '书（名词，单数）' }, answer: 'en bok' },
    { id: 'b3_vocab_dator', kind: 'vocab_spelling', concept: 'dator', lemma: 'dator', source: 'vocab', prompt: { zh: '电脑（名词，单数）' }, answer: 'en dator' },
    { id: 'b3_vocab_timme', kind: 'vocab_spelling', concept: 'timme', lemma: 'timme', source: 'vocab', prompt: { zh: '小时（名词，单数）' }, answer: 'en timme' },
    { id: 'b3_vocab_vecka', kind: 'vocab_spelling', concept: 'vecka', lemma: 'vecka', source: 'vocab', prompt: { zh: '周（名词，单数）' }, answer: 'en vecka' },
    { id: 'b3_vocab_ar', kind: 'vocab_spelling', concept: 'år', lemma: 'år', source: 'vocab', prompt: { zh: '年（名词，单数）' }, answer: 'ett år' },
    { id: 'b3_vocab_skola', kind: 'vocab_spelling', concept: 'skola', lemma: 'skola', source: 'vocab', prompt: { zh: '学校（名词，单数）' }, answer: 'en skola' },
    // ===== 固定表达题 =====
    { id: 'b3_phrase_jag_har_tre_bilar', kind: 'phrase_fill', concept: 'jag_har_tre_bilar', lemma: 'bilar', source: 'phrase', prompt: { zh: '我有三辆汽车。' }, template: 'Jag har tre {{bilar}}.' },
    { id: 'b3_phrase_vi_har_manga_bocker', kind: 'phrase_fill', concept: 'vi_har_manga_bocker', lemma: 'böcker', source: 'phrase', prompt: { zh: '我们有很多书。' }, template: 'Vi har många {{böcker}}.' },
    { id: 'b3_phrase_vi_behover_fler_datorer', kind: 'phrase_fill', concept: 'vi_behover_fler_datorer', lemma: 'datorer', source: 'phrase', prompt: { zh: '我们需要更多电脑。' }, template: 'Vi behöver fler {{datorer}}.' },
    { id: 'b3_phrase_det_finns_tre_familjer', kind: 'phrase_fill', concept: 'det_finns_tre_familjer', lemma: 'familjer', source: 'phrase', prompt: { zh: '楼里有三个家庭。' }, template: 'Det finns tre {{familjer}} i huset.' },
    { id: 'b3_phrase_jag_ser_deras_cyklar', kind: 'phrase_fill', concept: 'jag_ser_deras_cyklar', lemma: 'cyklar', source: 'phrase', prompt: { zh: '我每天看到他们的自行车。' }, template: 'Jag ser deras {{cyklar}} varje dag.' },
    { id: 'b3_phrase_den_har_tre_rum', kind: 'phrase_fill', concept: 'den_har_tre_rum', lemma: 'rum', source: 'phrase', prompt: { zh: '新公寓有三个房间。' }, template: 'Den har tre {{rum}}.' },
    { id: 'b3_phrase_det_finns_manga_fonster', kind: 'phrase_fill', concept: 'det_finns_manga_fonster', lemma: 'fönster', source: 'phrase', prompt: { zh: '有很多窗户，所以很明亮。' }, template: 'Det finns många {{fönster}}, så det är ljust.' },
    { id: 'b3_phrase_jag_kopte_tva_stolar', kind: 'phrase_fill', concept: 'jag_kopte_tva_stolar', lemma: 'stolar', source: 'phrase', prompt: { zh: '我买了两把椅子和一张桌子。' }, template: 'Jag köpte två {{stolar}} och ett bord.' },
    { id: 'b3_phrase_vi_ar_tjugo_elever', kind: 'phrase_fill', concept: 'vi_ar_tjugo_elever', lemma: 'elever', source: 'phrase', prompt: { zh: '我们班有二十个学生。' }, template: 'Vi är tjugo {{elever}}.' },
    { id: 'b3_phrase_femton_timmar_varje_vecka', kind: 'phrase_fill', concept: 'femton_timmar_varje_vecka', lemma: 'timmar', source: 'phrase', prompt: { zh: '我每周学十五个小时瑞典语。' }, template: 'Jag studerar ungefär femton {{timmar}} varje vecka.' },
    // ===== 对话句题 =====
    { id: 'b3_dialog_hur_manga_rum_har_den', kind: 'dialog_fill', concept: 'hur_manga_rum_har_den', lemma: 'rum', source: 'dialog', prompt: { zh: '你的新公寓有几个房间？' }, template: 'Hur många {{rum}} har din nya lägenhet?' },
    { id: 'b3_dialog_den_har_tre_rum', kind: 'dialog_fill', concept: 'den_har_tre_rum_dialog', lemma: 'rum', source: 'dialog', prompt: { zh: '它有三个房间。' }, template: 'Den har tre {{rum}}.' },
    { id: 'b3_dialog_det_finns_manga_fonster', kind: 'dialog_fill', concept: 'det_finns_manga_fonster_dialog', lemma: 'fönster', source: 'dialog', prompt: { zh: '也有很多窗户。' }, template: 'Det finns många {{fönster}}.' },
    { id: 'b3_dialog_har_du_kopt_nya_mobler', kind: 'dialog_fill', concept: 'har_du_kopt_nya_mobler', lemma: 'möbler', source: 'dialog', prompt: { zh: '你买新家具了吗？' }, template: 'Har du köpt några nya {{möbler}}?' },
    { id: 'b3_dialog_jag_kopte_tva_stolar_och_ett_bord', kind: 'dialog_fill', concept: 'jag_kopte_tva_stolar_och_ett_bord', lemma: 'stolar', source: 'dialog', prompt: { zh: '是的，我买了两把椅子和一张桌子。' }, template: 'Jag köpte två {{stolar}} och ett bord.' },
    { id: 'b3_dialog_bor_det_manga_barn', kind: 'dialog_fill', concept: 'bor_det_manga_barn', lemma: 'barn', source: 'dialog', prompt: { zh: '楼里住着很多孩子吗？' }, template: 'Bor det många {{barn}} i huset?' },
    { id: 'b3_dialog_det_finns_tre_familjer_med_barn', kind: 'dialog_fill', concept: 'det_finns_tre_familjer_med_barn', lemma: 'familjer', source: 'dialog', prompt: { zh: '有三个有孩子的家庭。' }, template: 'Det finns tre {{familjer}} med barn.' },
    { id: 'b3_dialog_jag_ser_deras_cyklar_utanfor', kind: 'dialog_fill', concept: 'jag_ser_deras_cyklar_utanfor', lemma: 'cyklar', source: 'dialog', prompt: { zh: '我每天都能看到他们的自行车。' }, template: 'Jag ser deras {{cyklar}} utanför varje dag.' },
    { id: 'b3_dialog_hur_manga_elever_ar_det', kind: 'dialog_fill', concept: 'hur_manga_elever_ar_det', lemma: 'elever', source: 'dialog', prompt: { zh: '你们班有多少学生？' }, template: 'Hur många {{elever}} är det i din klass?' },
    { id: 'b3_dialog_vi_ar_tjugo_elever', kind: 'dialog_fill', concept: 'vi_ar_tjugo_elever_dialog', lemma: 'elever', source: 'dialog', prompt: { zh: '我们有二十个学生。' }, template: 'Vi är tjugo {{elever}}.' },
    { id: 'b3_dialog_har_ni_bra_bocker_och_datorer', kind: 'dialog_fill', concept: 'har_ni_bra_bocker_och_datorer', lemma: 'böcker datorer', source: 'dialog', prompt: { zh: '你们有好书和电脑吗？' }, template: 'Har ni bra {{böcker}} och {{datorer}}?' },
    { id: 'b3_dialog_vi_har_manga_bocker', kind: 'dialog_fill', concept: 'vi_har_manga_bocker_dialog', lemma: 'böcker', source: 'dialog', prompt: { zh: '我们有很多书。' }, template: 'Vi har många {{böcker}}.' },
    { id: 'b3_dialog_vi_behover_fler_datorer', kind: 'dialog_fill', concept: 'vi_behover_fler_datorer_dialog', lemma: 'datorer', source: 'dialog', prompt: { zh: '但我们需要更多电脑。' }, template: 'Men vi behöver fler {{datorer}}.' },
    { id: 'b3_dialog_hur_manga_timmar_studerar_du', kind: 'dialog_fill', concept: 'hur_manga_timmar_studerar_du', lemma: 'timmar', source: 'dialog', prompt: { zh: '每周你学多少小时瑞典语？' }, template: 'Hur många {{timmar}} studerar du svenska varje vecka?' },
    { id: 'b3_dialog_jag_studerar_femton_timmar', kind: 'dialog_fill', concept: 'jag_studerar_femton_timmar', lemma: 'timmar', source: 'dialog', prompt: { zh: '我在学校学大约十五个小时。' }, template: 'Jag studerar ungefär femton {{timmar}} i skolan.' },
    { id: 'b3_dialog_jag_laser_bocker_hemma', kind: 'dialog_fill', concept: 'jag_laser_bocker_hemma', lemma: 'böcker', source: 'dialog', prompt: { zh: '晚上我在家读书。' }, template: 'Jag läser {{böcker}} hemma på kvällarna.' }
  ],
  advancedPool: [
    // ===== 名词变形 =====
    { id: 'b3_noun_hus_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'hus', prompt: { zh: '房子' }, template: '{{ett}} | {{hus}} | {{huset}} | {{hus}} | {{husen}}' },
    { id: 'b3_noun_rum_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'rum', prompt: { zh: '房间' }, template: '{{ett}} | {{rum}} | {{rummet}} | {{rum}} | {{rummen}}' },
    { id: 'b3_noun_barn_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'barn', prompt: { zh: '孩子' }, template: '{{ett}} | {{barn}} | {{barnet}} | {{barn}} | {{barnen}}' },
    { id: 'b3_noun_ar_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'år', prompt: { zh: '年' }, template: '{{ett}} | {{år}} | {{året}} | {{år}} | {{åren}}' },
    { id: 'b3_noun_fonster_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'fönster', prompt: { zh: '窗户' }, template: '{{ett}} | {{fönster}} | {{fönstret}} | {{fönster}} | {{fönstren}}' },
    { id: 'b3_noun_vecka_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'vecka', prompt: { zh: '周' }, template: '{{en}} | {{vecka}} | {{veckan}} | {{veckor}} | {{veckorna}}' },
    { id: 'b3_noun_skola_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'skola', prompt: { zh: '学校' }, template: '{{en}} | {{skola}} | {{skolan}} | {{skolor}} | {{skolorna}}' },
    { id: 'b3_noun_stol_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'stol', prompt: { zh: '椅子' }, template: '{{en}} | {{stol}} | {{stolen}} | {{stolar}} | {{stolarna}}' },
    { id: 'b3_noun_cykel_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'cykel', prompt: { zh: '自行车' }, template: '{{en}} | {{cykel}} | {{cykeln}} | {{cyklar}} | {{cyklarna}}' },
    { id: 'b3_noun_hand_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'hand', prompt: { zh: '手' }, template: '{{en}} | {{hand}} | {{handen}} | {{händer}} | {{händerna}}' },
    { id: 'b3_noun_mobel_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'möbel', prompt: { zh: '家具' }, template: '{{en}} | {{möbel}} | {{möbeln}} | {{möbler}} | {{möblerna}}' },
    { id: 'b3_noun_familj_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'familj', prompt: { zh: '家庭' }, template: '{{en}} | {{familj}} | {{familjen}} | {{familjer}} | {{familjerna}}' },
    { id: 'b3_noun_elev_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'elev', prompt: { zh: '学生' }, template: '{{en}} | {{elev}} | {{eleven}} | {{elever}} | {{eleverna}}' },
    { id: 'b3_noun_dator_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'dator', prompt: { zh: '电脑' }, template: '{{en}} | {{dator}} | {{datorn}} | {{datorer}} | {{datorerna}}' },
    { id: 'b3_noun_bok_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'bok', prompt: { zh: '书' }, template: '{{en}} | {{bok}} | {{boken}} | {{böcker}} | {{böckerna}}' },
    { id: 'b3_noun_yrke_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'yrke', prompt: { zh: '职业' }, template: '{{ett}} | {{yrke}} | {{yrket}} | {{yrken}} | {{yrkena}}' },
    // ===== 结构专项：数量结构 =====
    { id: 'b3_struct_tre_bilar', kind: 'morphology', source: 'pattern', lemma: 'tre bilar', prompt: { zh: 'three + car' }, template: 'tre {{bilar}}' },
    { id: 'b3_struct_manga_bocker', kind: 'morphology', source: 'pattern', lemma: 'många böcker', prompt: { zh: 'many + books' }, template: 'många {{böcker}}' },
    { id: 'b3_struct_fler_datorer', kind: 'morphology', source: 'pattern', lemma: 'fler datorer', prompt: { zh: 'more + computers' }, template: 'fler {{datorer}}' },
    { id: 'b3_struct_femton_timmar', kind: 'morphology', source: 'pattern', lemma: 'femton timmar', prompt: { zh: 'fifteen + hours' }, template: 'femton {{timmar}}' }
  ]
};
