window.UNIT_BANK_B4 = {
  unit: 'b4',
  unitTitle: '基础句型与否定句',
  basicPool: [
    // ===== 单词题 =====
    { id: 'b4_vocab_frukost', kind: 'vocab_spelling', concept: 'frukost', lemma: 'frukost', source: 'vocab', prompt: { zh: '早饭（名词，单数）' }, answer: 'en frukost' },
    { id: 'b4_vocab_middag', kind: 'vocab_spelling', concept: 'middag', lemma: 'middag', source: 'vocab', prompt: { zh: '午饭 / 晚饭（名词，单数）' }, answer: 'en middag' },
    { id: 'b4_vocab_kaffe', kind: 'vocab_spelling', concept: 'kaffe', lemma: 'kaffe', source: 'vocab', prompt: { zh: '咖啡（名词，单数）' }, answer: 'en kaffe' },
    { id: 'b4_vocab_fraga', kind: 'vocab_spelling', concept: 'fråga', lemma: 'fråga', source: 'vocab', prompt: { zh: '问题 / 提问（名词，单数）' }, answer: 'en fråga' },
    { id: 'b4_vocab_svar', kind: 'vocab_spelling', concept: 'svar', lemma: 'svar', source: 'vocab', prompt: { zh: '回答（名词，单数）' }, answer: 'ett svar' },
    { id: 'b4_vocab_mening', kind: 'vocab_spelling', concept: 'mening', lemma: 'mening', source: 'vocab', prompt: { zh: '句子 / 意思（名词，单数）' }, answer: 'en mening' },
    { id: 'b4_vocab_ord', kind: 'vocab_spelling', concept: 'ord', lemma: 'ord', source: 'vocab', prompt: { zh: '单词（名词，单数）' }, answer: 'ett ord' },
    { id: 'b4_vocab_telefon', kind: 'vocab_spelling', concept: 'telefon', lemma: 'telefon', source: 'vocab', prompt: { zh: '电话（名词，单数）' }, answer: 'en telefon' },
    { id: 'b4_vocab_lunch', kind: 'vocab_spelling', concept: 'lunch', lemma: 'lunch', source: 'vocab', prompt: { zh: '午餐（名词，单数）' }, answer: 'en lunch' },
    { id: 'b4_vocab_tid', kind: 'vocab_spelling', concept: 'tid', lemma: 'tid', source: 'vocab', prompt: { zh: '时间 / 预约（名词，单数）' }, answer: 'en tid' },
    { id: 'b4_vocab_kort', kind: 'vocab_spelling', concept: 'kort', lemma: 'kort', source: 'vocab', prompt: { zh: '卡（名词，单数）' }, answer: 'ett kort' },
    { id: 'b4_vocab_problem', kind: 'vocab_spelling', concept: 'problem', lemma: 'problem', source: 'vocab', prompt: { zh: '问题（名词，单数）' }, answer: 'ett problem' },
    { id: 'b4_vocab_ata', kind: 'vocab_spelling', concept: 'äta', lemma: 'äta', source: 'vocab', prompt: { zh: '吃（动词原形）' }, answer: 'äta' },
    { id: 'b4_vocab_dricka', kind: 'vocab_spelling', concept: 'dricka', lemma: 'dricka', source: 'vocab', prompt: { zh: '喝（动词原形）' }, answer: 'dricka' },
    { id: 'b4_vocab_bo', kind: 'vocab_spelling', concept: 'bo', lemma: 'bo', source: 'vocab', prompt: { zh: '住（动词原形）' }, answer: 'bo' },
    { id: 'b4_vocab_arbeta', kind: 'vocab_spelling', concept: 'arbeta', lemma: 'arbeta', source: 'vocab', prompt: { zh: '工作（动词原形）' }, answer: 'arbeta' },
    { id: 'b4_vocab_komma', kind: 'vocab_spelling', concept: 'komma', lemma: 'komma', source: 'vocab', prompt: { zh: '来（动词原形）' }, answer: 'komma' },
    { id: 'b4_vocab_hjalpa', kind: 'vocab_spelling', concept: 'hjälpa', lemma: 'hjälpa', source: 'vocab', prompt: { zh: '帮助（动词原形）' }, answer: 'hjälpa' },
    { id: 'b4_vocab_forsta', kind: 'vocab_spelling', concept: 'förstå', lemma: 'förstå', source: 'vocab', prompt: { zh: '理解（动词原形）' }, answer: 'förstå' },
    { id: 'b4_vocab_vilja', kind: 'vocab_spelling', concept: 'vilja', lemma: 'vilja', source: 'vocab', prompt: { zh: '想要（动词原形）' }, answer: 'vilja' },
    { id: 'b4_vocab_ha_med_sig', kind: 'vocab_spelling', concept: 'ha_med_sig', lemma: 'ha med sig', source: 'vocab', prompt: { zh: '带着 / 携带（动词原形）' }, answer: 'ha med sig' },
    { id: 'b4_vocab_ta_med_sig', kind: 'vocab_spelling', concept: 'ta_med_sig', lemma: 'ta med sig', source: 'vocab', prompt: { zh: '带着 / 携带（动词原形）' }, answer: 'ta med sig' },
    { id: 'b4_vocab_hungrig', kind: 'vocab_spelling', concept: 'hungrig', lemma: 'hungrig', source: 'vocab', prompt: { zh: '饿的' }, answer: 'hungrig' },
    { id: 'b4_vocab_kall', kind: 'vocab_spelling', concept: 'kall', lemma: 'kall', source: 'vocab', prompt: { zh: '冷的' }, answer: 'kall' },
    { id: 'b4_vocab_vad', kind: 'vocab_spelling', concept: 'vad', lemma: 'vad', source: 'vocab', prompt: { zh: '什么' }, answer: 'vad' },
    { id: 'b4_vocab_var', kind: 'vocab_spelling', concept: 'var', lemma: 'var', source: 'vocab', prompt: { zh: '在哪里' }, answer: 'var' },
    { id: 'b4_vocab_hur', kind: 'vocab_spelling', concept: 'hur', lemma: 'hur', source: 'vocab', prompt: { zh: '怎么 / 如何' }, answer: 'hur' },
    { id: 'b4_vocab_inte', kind: 'vocab_spelling', concept: 'inte', lemma: 'inte', source: 'vocab', prompt: { zh: '不' }, answer: 'inte' },
    { id: 'b4_vocab_aldrig', kind: 'vocab_spelling', concept: 'aldrig', lemma: 'aldrig', source: 'vocab', prompt: { zh: '从不' }, answer: 'aldrig' },
    { id: 'b4_vocab_inga', kind: 'vocab_spelling', concept: 'inga', lemma: 'inga', source: 'vocab', prompt: { zh: '没有（复数）' }, answer: 'inga' },
    // ===== 固定表达题 =====
    { id: 'b4_phrase_jag_ater_frukost', kind: 'phrase_fill', concept: 'jag_ater_frukost', lemma: 'äter', source: 'phrase', prompt: { zh: '我吃早饭。' }, template: 'Jag {{äter}} frukost.' },
    { id: 'b4_phrase_hon_bor_i_goteborg', kind: 'phrase_fill', concept: 'hon_bor_i_goteborg', lemma: 'bor', source: 'phrase', prompt: { zh: '她住在哥德堡。' }, template: 'Hon {{bor}} i Göteborg.' },
    { id: 'b4_phrase_det_ar_kallt_idag', kind: 'phrase_fill', concept: 'det_ar_kallt_idag', lemma: 'är', source: 'phrase', prompt: { zh: '今天很冷。' }, template: 'Det {{är}} kallt idag.' },
    { id: 'b4_phrase_ater_du_frukost', kind: 'phrase_fill', concept: 'ater_du_frukost', lemma: 'äter', source: 'phrase', prompt: { zh: '你吃早饭吗？' }, template: '{{Äter}} du frukost?' },
    { id: 'b4_phrase_bor_du_i_stockholm', kind: 'phrase_fill', concept: 'bor_du_i_stockholm', lemma: 'bor', source: 'phrase', prompt: { zh: '你住在斯德哥尔摩吗？' }, template: '{{Bor}} du i Stockholm?' },
    { id: 'b4_phrase_har_du_en_syster', kind: 'phrase_fill', concept: 'har_du_en_syster', lemma: 'har', source: 'phrase', prompt: { zh: '你有姐妹吗？' }, template: '{{Har}} du en syster?' },
    { id: 'b4_phrase_vad_ater_du', kind: 'phrase_fill', concept: 'vad_ater_du', lemma: 'vad', source: 'phrase', prompt: { zh: '你吃什么？' }, template: '{{Vad}} äter du?' },
    { id: 'b4_phrase_var_bor_du', kind: 'phrase_fill', concept: 'var_bor_du', lemma: 'var', source: 'phrase', prompt: { zh: '你住在哪里？' }, template: '{{Var}} bor du?' },
    { id: 'b4_phrase_hur_mar_du', kind: 'phrase_fill', concept: 'hur_mar_du', lemma: 'hur', source: 'phrase', prompt: { zh: '你好吗？' }, template: '{{Hur}} mår du?' },
    { id: 'b4_phrase_jag_ater_inte_frukost_idag', kind: 'phrase_fill', concept: 'jag_ater_inte_frukost_idag', lemma: 'inte', source: 'phrase', prompt: { zh: '我今天不吃早饭。' }, template: 'Jag äter {{inte}} frukost idag.' },
    { id: 'b4_phrase_hon_ater_aldrig_kott', kind: 'phrase_fill', concept: 'hon_ater_aldrig_kott', lemma: 'aldrig', source: 'phrase', prompt: { zh: '她从不吃肉。' }, template: 'Hon äter {{aldrig}} kött.' },
    { id: 'b4_phrase_det_finns_inga_applen_kvar', kind: 'phrase_fill', concept: 'det_finns_inga_applen_kvar', lemma: 'inga', source: 'phrase', prompt: { zh: '没有苹果了。' }, template: 'Det finns {{inga}} äpplen kvar.' },
    { id: 'b4_phrase_jag_vet_att_han_inte_kommer', kind: 'phrase_fill', concept: 'jag_vet_att_han_inte_kommer', lemma: 'inte', source: 'phrase', prompt: { zh: '我知道他明天不来。' }, template: 'Jag vet att han {{inte}} kommer imorgon.' },
    { id: 'b4_phrase_hon_arbetar_inte_idag', kind: 'phrase_fill', concept: 'hon_arbetar_inte_idag', lemma: 'inte', source: 'phrase', prompt: { zh: '她今天不工作。' }, template: 'Hon arbetar {{inte}} idag.' },
    { id: 'b4_phrase_idag_arbetar_jag_hemma', kind: 'phrase_fill', concept: 'idag_arbetar_jag_hemma', lemma: 'arbetar', source: 'phrase', prompt: { zh: '今天我在家工作。' }, template: 'Idag {{arbetar}} jag hemma.' },
    { id: 'b4_phrase_ofta_ater_vi_pizza', kind: 'phrase_fill', concept: 'ofta_ater_vi_pizza', lemma: 'äter', source: 'phrase', prompt: { zh: '我们经常吃披萨。' }, template: 'Ofta {{äter}} vi pizza.' },
    { id: 'b4_phrase_imorgon_arbetar_jag_inte', kind: 'phrase_fill', concept: 'imorgon_arbetar_jag_inte', lemma: 'arbetar', source: 'phrase', prompt: { zh: '明天我不上班。' }, template: 'Imorgon {{arbetar}} jag inte.' },
    // ===== 对话句题 =====
    { id: 'b4_dialog_vad_vill_du_ha', kind: 'dialog_fill', concept: 'vad_vill_du_ha', lemma: 'vad', source: 'dialog', prompt: { zh: '你想要什么？' }, template: '{{Vad}} vill du ha?' },
    { id: 'b4_dialog_jag_vill_ha_en_kaffe', kind: 'dialog_fill', concept: 'jag_vill_ha_en_kaffe', lemma: 'kaffe', source: 'dialog', prompt: { zh: '我想要一杯咖啡，谢谢。' }, template: 'Jag vill ha en {{kaffe}}, tack.' },
    { id: 'b4_dialog_men_jag_vill_inte_ha_socker', kind: 'dialog_fill', concept: 'men_jag_vill_inte_ha_socker', lemma: 'inte', source: 'dialog', prompt: { zh: '但我不要糖。' }, template: 'Men jag vill {{inte}} ha socker.' },
    { id: 'b4_dialog_vill_du_ha_nagot_att_ata', kind: 'dialog_fill', concept: 'vill_du_ha_nagot_att_ata', lemma: 'vill', source: 'dialog', prompt: { zh: '你想吃点什么吗？' }, template: '{{Vill}} du ha något att äta?' },
    { id: 'b4_dialog_nej_jag_ar_inte_hungrig', kind: 'dialog_fill', concept: 'nej_jag_ar_inte_hungrig', lemma: 'inte', source: 'dialog', prompt: { zh: '不，我不饿。' }, template: 'Nej, jag är {{inte}} hungrig.' },
    { id: 'b4_dialog_jag_ater_aldrig_pa_formiddagen', kind: 'dialog_fill', concept: 'jag_ater_aldrig_pa_formiddagen', lemma: 'aldrig', source: 'dialog', prompt: { zh: '我早上从来不吃东西。' }, template: 'Jag äter {{aldrig}} på förmiddagen.' },
    { id: 'b4_dialog_hur_mycket_kostar_det', kind: 'dialog_fill', concept: 'hur_mycket_kostar_det', lemma: 'hur', source: 'dialog', prompt: { zh: '多少钱？' }, template: '{{Hur}} mycket kostar det?' },
    { id: 'b4_dialog_vi_tar_inte_kontanter', kind: 'dialog_fill', concept: 'vi_tar_inte_kontanter', lemma: 'inte', source: 'dialog', prompt: { zh: '我们不收现金，只收卡。' }, template: 'Vi tar {{inte}} kontanter, bara kort.' },
    { id: 'b4_dialog_hej_jag_kan_inte_komma_nu', kind: 'dialog_fill', concept: 'hej_jag_kan_inte_komma_nu', lemma: 'inte', source: 'dialog', prompt: { zh: '你好，我现在不能来。' }, template: 'Hej, jag kan {{inte}} komma nu.' },
    { id: 'b4_dialog_jag_arbetar_inte_idag', kind: 'dialog_fill', concept: 'jag_arbetar_inte_idag_dialog', lemma: 'inte', source: 'dialog', prompt: { zh: '我今天不上班。' }, template: 'Jag arbetar {{inte}} idag.' },
    { id: 'b4_dialog_har_du_tid_imorgon', kind: 'dialog_fill', concept: 'har_du_tid_imorgon', lemma: 'tid', source: 'dialog', prompt: { zh: '你明天有时间吗？' }, template: 'Har du {{tid}} imorgon?' },
    { id: 'b4_dialog_jag_har_inte_personnummer_med_mig', kind: 'dialog_fill', concept: 'jag_har_inte_personnummer_med_mig', lemma: 'inte', source: 'dialog', prompt: { zh: '我现在没带个人编号，但我可以回电话。' }, template: 'Jag har {{inte}} personnummer med mig nu, men jag kan ringa tillbaka.' }
  ],
  advancedPool: [
    // ===== noun_forms =====
    { id: 'b4_noun_frukost_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'frukost', prompt: { zh: '早饭' }, template: '{{en}} | {{frukost}} | {{frukosten}} | {{frukoster}} | {{frukosterna}}' },
    { id: 'b4_noun_middag_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'middag', prompt: { zh: '午饭 / 晚饭' }, template: '{{en}} | {{middag}} | {{middagen}} | {{middagar}} | {{middagarna}}' },
    { id: 'b4_noun_kaffe_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'kaffe', prompt: { zh: '咖啡' }, template: '{{en}} | {{kaffe}} | {{kaffet}} | {{kaffen}} | {{kaffena}}' },
    { id: 'b4_noun_fraga_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'fråga', prompt: { zh: '问题 / 提问' }, template: '{{en}} | {{fråga}} | {{frågan}} | {{frågor}} | {{frågorna}}' },
    { id: 'b4_noun_svar_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'svar', prompt: { zh: '回答' }, template: '{{ett}} | {{svar}} | {{svaret}} | {{svar}} | {{svaren}}' },
    { id: 'b4_noun_mening_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'mening', prompt: { zh: '句子 / 意思' }, template: '{{en}} | {{mening}} | {{meningen}} | {{meningar}} | {{meningarna}}' },
    { id: 'b4_noun_ord_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'ord', prompt: { zh: '单词' }, template: '{{ett}} | {{ord}} | {{ordet}} | {{ord}} | {{orden}}' },
    { id: 'b4_noun_telefon_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'telefon', prompt: { zh: '电话' }, template: '{{en}} | {{telefon}} | {{telefonen}} | {{telefoner}} | {{telefonerna}}' },
    { id: 'b4_noun_lunch_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'lunch', prompt: { zh: '午餐' }, template: '{{en}} | {{lunch}} | {{lunchen}} | {{luncher}} | {{luncherna}}' },
    { id: 'b4_noun_tid_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'tid', prompt: { zh: '时间 / 预约' }, template: '{{en}} | {{tid}} | {{tiden}} | {{tider}} | {{tiderna}}' },
    { id: 'b4_noun_kort_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'kort', prompt: { zh: '卡' }, template: '{{ett}} | {{kort}} | {{kortet}} | {{kort}} | {{korten}}' },
    { id: 'b4_noun_problem_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'problem', prompt: { zh: '问题' }, template: '{{ett}} | {{problem}} | {{problemet}} | {{problem}} | {{problemen}}' },
    // ===== verb_forms =====
    { id: 'b4_verb_ata_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'äta', prompt: { zh: '吃' }, template: '{{äta}} | {{äter}} | {{åt}} | {{ätit}}' },
    { id: 'b4_verb_dricka_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'dricka', prompt: { zh: '喝' }, template: '{{dricka}} | {{dricker}} | {{drack}} | {{druckit}}' },
    { id: 'b4_verb_bo_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'bo', prompt: { zh: '住' }, template: '{{bo}} | {{bor}} | {{bodde}} | {{bott}}' },
    { id: 'b4_verb_arbeta_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'arbeta', prompt: { zh: '工作' }, template: '{{arbeta}} | {{arbetar}} | {{arbetade}} | {{arbetat}}' },
    { id: 'b4_verb_komma_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'komma', prompt: { zh: '来' }, template: '{{komma}} | {{kommer}} | {{kom}} | {{kommit}}' },
    { id: 'b4_verb_hjalpa_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'hjälpa', prompt: { zh: '帮助' }, template: '{{hjälpa}} | {{hjälper}} | {{hjälpte}} | {{hjälpt}}' },
    { id: 'b4_verb_forsta_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'förstå', prompt: { zh: '理解' }, template: '{{förstå}} | {{förstår}} | {{förstod}} | {{förstått}}' },
    { id: 'b4_verb_vilja_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'vilja', prompt: { zh: '想要' }, template: '{{vilja}} | {{vill}} | {{ville}} | {{velat}}' },
    // ===== adjective / pattern =====
    { id: 'b4_adj_hungrig_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'hungrig', prompt: { zh: '饿的' }, template: '{{hungrig}} | {{hungrigt}} | {{hungriga}}' },
    { id: 'b4_adj_kall_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'kall', prompt: { zh: '冷的' }, template: '{{kall}} | {{kallt}} | {{kalla}}' },
    { id: 'b4_adj_bra_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'bra', prompt: { zh: '好的' }, template: '{{bra}} | {{bra}} | {{bra}}', autoPlay: false },
    // ===== negation pattern =====
    { id: 'b4_neg_jag_ater_inte_frukost_idag', kind: 'morphology', source: 'pattern', lemma: 'jag äter inte frukost idag', prompt: { zh: '我今天不吃早饭。' }, template: 'Jag äter {{inte}} frukost idag.' },
    { id: 'b4_neg_jag_vet_att_han_inte_kommer', kind: 'morphology', source: 'pattern', lemma: 'jag vet att han inte kommer imorgon', prompt: { zh: '我知道他明天不来。' }, template: 'Jag vet att han {{inte}} kommer imorgon.' },
    { id: 'b4_neg_det_finns_inga_applen_kvar', kind: 'morphology', source: 'pattern', lemma: 'det finns inga äpplen kvar', prompt: { zh: '没有苹果了。' }, template: 'Det finns {{inga}} äpplen kvar.' },
    { id: 'b4_neg_hon_ater_aldrig_kott', kind: 'morphology', source: 'pattern', lemma: 'hon äter aldrig kött', prompt: { zh: '她从不吃肉。' }, template: 'Hon äter {{aldrig}} kött.' }
  ]
};
