window.UNIT_BANK_B5 = {
  unit: 'b5',
  unitTitle: '形容词变格与比较级',
  basicPool: [
    // ===== 单词题 =====
    { id: 'b5_vocab_stor', kind: 'vocab_spelling', concept: 'stor', lemma: 'stor', source: 'vocab', prompt: { zh: '大的' }, answer: 'stor' },
    { id: 'b5_vocab_liten', kind: 'vocab_spelling', concept: 'liten', lemma: 'liten', source: 'vocab', prompt: { zh: '小的' }, answer: 'liten' },
    { id: 'b5_vocab_ny', kind: 'vocab_spelling', concept: 'ny', lemma: 'ny', source: 'vocab', prompt: { zh: '新的' }, answer: 'ny' },
    { id: 'b5_vocab_gammal', kind: 'vocab_spelling', concept: 'gammal', lemma: 'gammal', source: 'vocab', prompt: { zh: '旧的 / 老的' }, answer: 'gammal' },
    { id: 'b5_vocab_bra', kind: 'vocab_spelling', concept: 'bra', lemma: 'bra', source: 'vocab', prompt: { zh: '好的' }, answer: 'bra' },
    { id: 'b5_vocab_dalig', kind: 'vocab_spelling', concept: 'dålig', lemma: 'dålig', source: 'vocab', prompt: { zh: '差的 / 坏的' }, answer: 'dålig' },
    { id: 'b5_vocab_billig', kind: 'vocab_spelling', concept: 'billig', lemma: 'billig', source: 'vocab', prompt: { zh: '便宜的' }, answer: 'billig' },
    { id: 'b5_vocab_dyr', kind: 'vocab_spelling', concept: 'dyr', lemma: 'dyr', source: 'vocab', prompt: { zh: '贵的' }, answer: 'dyr' },
    { id: 'b5_vocab_snabb', kind: 'vocab_spelling', concept: 'snabb', lemma: 'snabb', source: 'vocab', prompt: { zh: '快的' }, answer: 'snabb' },
    { id: 'b5_vocab_langsam', kind: 'vocab_spelling', concept: 'långsam', lemma: 'långsam', source: 'vocab', prompt: { zh: '慢的' }, answer: 'långsam' },
    { id: 'b5_vocab_varm', kind: 'vocab_spelling', concept: 'varm', lemma: 'varm', source: 'vocab', prompt: { zh: '热的 / 温暖的' }, answer: 'varm' },
    { id: 'b5_vocab_kall', kind: 'vocab_spelling', concept: 'kall', lemma: 'kall', source: 'vocab', prompt: { zh: '冷的' }, answer: 'kall' },
    { id: 'b5_vocab_latt', kind: 'vocab_spelling', concept: 'lätt', lemma: 'lätt', source: 'vocab', prompt: { zh: '轻的 / 容易的' }, answer: 'lätt' },
    { id: 'b5_vocab_svar', kind: 'vocab_spelling', concept: 'svår', lemma: 'svår', source: 'vocab', prompt: { zh: '难的 / 重的' }, answer: 'svår' },
    { id: 'b5_vocab_ung', kind: 'vocab_spelling', concept: 'ung', lemma: 'ung', source: 'vocab', prompt: { zh: '年轻的' }, answer: 'ung' },
    { id: 'b5_vocab_trott', kind: 'vocab_spelling', concept: 'trött', lemma: 'trött', source: 'vocab', prompt: { zh: '累的' }, answer: 'trött' },
    { id: 'b5_vocab_glad', kind: 'vocab_spelling', concept: 'glad', lemma: 'glad', source: 'vocab', prompt: { zh: '高兴的' }, answer: 'glad' },
    { id: 'b5_vocab_ledsen', kind: 'vocab_spelling', concept: 'ledsen', lemma: 'ledsen', source: 'vocab', prompt: { zh: '伤心的 / 抱歉的' }, answer: 'ledsen' },
    { id: 'b5_vocab_lagenhet', kind: 'vocab_spelling', concept: 'lägenhet', lemma: 'lägenhet', source: 'vocab', prompt: { zh: '公寓（名词，单数）' }, answer: 'en lägenhet' },
    { id: 'b5_vocab_rum', kind: 'vocab_spelling', concept: 'rum', lemma: 'rum', source: 'vocab', prompt: { zh: '房间（名词，单数）' }, answer: 'ett rum' },
    { id: 'b5_vocab_hyra', kind: 'vocab_spelling', concept: 'hyra', lemma: 'hyra', source: 'vocab', prompt: { zh: '租金（名词，单数）' }, answer: 'en hyra' },
    { id: 'b5_vocab_val', kind: 'vocab_spelling', concept: 'val', lemma: 'val', source: 'vocab', prompt: { zh: '选择（名词，单数）' }, answer: 'ett val' },
    { id: 'b5_vocab_cykel', kind: 'vocab_spelling', concept: 'cykel', lemma: 'cykel', source: 'vocab', prompt: { zh: '自行车（名词，单数）' }, answer: 'en cykel' },
    { id: 'b5_vocab_skick', kind: 'vocab_spelling', concept: 'skick', lemma: 'skick', source: 'vocab', prompt: { zh: '状态 / 状况（名词，单数）' }, answer: 'ett skick' },
    { id: 'b5_vocab_verka', kind: 'vocab_spelling', concept: 'verka', lemma: 'verka', source: 'vocab', prompt: { zh: '似乎 / 好像（动词原形）' }, answer: 'verka' },
    { id: 'b5_vocab_behova', kind: 'vocab_spelling', concept: 'behöva', lemma: 'behöva', source: 'vocab', prompt: { zh: '需要（动词原形）' }, answer: 'behöva' },
    { id: 'b5_vocab_jamfora', kind: 'vocab_spelling', concept: 'jämföra', lemma: 'jämföra', source: 'vocab', prompt: { zh: '比较（动词原形）' }, answer: 'jämföra' },
    { id: 'b5_vocab_valja', kind: 'vocab_spelling', concept: 'välja', lemma: 'välja', source: 'vocab', prompt: { zh: '选择 / 选（动词原形）' }, answer: 'välja' },
    { id: 'b5_vocab_valdigt', kind: 'vocab_spelling', concept: 'väldigt', lemma: 'väldigt', source: 'vocab', prompt: { zh: '非常' }, answer: 'väldigt' },
    { id: 'b5_vocab_ganska', kind: 'vocab_spelling', concept: 'ganska', lemma: 'ganska', source: 'vocab', prompt: { zh: '相当 / 挺' }, answer: 'ganska' },
    { id: 'b5_vocab_lite', kind: 'vocab_spelling', concept: 'lite', lemma: 'lite', source: 'vocab', prompt: { zh: '一点 / 稍微' }, answer: 'lite' },
    { id: 'b5_vocab_mycket', kind: 'vocab_spelling', concept: 'mycket', lemma: 'mycket', source: 'vocab', prompt: { zh: '很 / 非常（程度）' }, answer: 'mycket' },
    { id: 'b5_vocab_ungefar', kind: 'vocab_spelling', concept: 'ungefär', lemma: 'ungefär', source: 'vocab', prompt: { zh: '大约' }, answer: 'ungefär' },
    { id: 'b5_vocab_nastan', kind: 'vocab_spelling', concept: 'nästan', lemma: 'nästan', source: 'vocab', prompt: { zh: '几乎' }, answer: 'nästan' },
    { id: 'b5_vocab_garna', kind: 'vocab_spelling', concept: 'gärna', lemma: 'gärna', source: 'vocab', prompt: { zh: '愿意地 / 请' }, answer: 'gärna' },
    { id: 'b5_vocab_faktiskt', kind: 'vocab_spelling', concept: 'faktiskt', lemma: 'faktiskt', source: 'vocab', prompt: { zh: '实际上 / 其实' }, answer: 'faktiskt' },
    // ===== 固定表达题 =====
    { id: 'b5_phrase_en_stor_bil', kind: 'phrase_fill', concept: 'en_stor_bil', lemma: 'stor', source: 'phrase', prompt: { zh: '一辆大车。' }, template: 'en {{stor}} bil' },
    { id: 'b5_phrase_ett_stort_hus', kind: 'phrase_fill', concept: 'ett_stort_hus', lemma: 'stort', source: 'phrase', prompt: { zh: '一座大房子。' }, template: 'ett {{stort}} hus' },
    { id: 'b5_phrase_stora_bilar', kind: 'phrase_fill', concept: 'stora_bilar', lemma: 'stora', source: 'phrase', prompt: { zh: '大车 / 大的车（复数）。' }, template: '{{stora}} bilar' },
    { id: 'b5_phrase_den_stora_bilen', kind: 'phrase_fill', concept: 'den_stora_bilen', lemma: 'stora', source: 'phrase', prompt: { zh: '那辆大车。' }, template: 'den {{stora}} bilen' },
    { id: 'b5_phrase_ett_snabbt_tag', kind: 'phrase_fill', concept: 'ett_snabbt_tag', lemma: 'snabbt', source: 'phrase', prompt: { zh: '一列快火车。' }, template: 'ett snabb{{t}} tåg' },
    { id: 'b5_phrase_ett_glatt_barn', kind: 'phrase_fill', concept: 'ett_glatt_barn', lemma: 'glatt', source: 'phrase', prompt: { zh: '开心的孩子。' }, template: 'ett {{glatt}} barn' },
    { id: 'b5_phrase_storre_an', kind: 'phrase_fill', concept: 'storre_an', lemma: 'större', source: 'phrase', prompt: { zh: '红色的车比蓝色的车大。' }, template: 'Den röda bilen är {{större}} än den blå.' },
    { id: 'b5_phrase_kallare_idag', kind: 'phrase_fill', concept: 'kallare_idag', lemma: 'kallare', source: 'phrase', prompt: { zh: '今天比昨天冷。' }, template: 'Det är {{kallare}} idag än igår.' },
    { id: 'b5_phrase_billigast', kind: 'phrase_fill', concept: 'billigast', lemma: 'billigast', source: 'phrase', prompt: { zh: '哪辆车最便宜？' }, template: 'Vilken bil är {{billigast}}?' },
    { id: 'b5_phrase_basta_valet', kind: 'phrase_fill', concept: 'basta_valet', lemma: 'bästa', source: 'phrase', prompt: { zh: '这是最好的选择。' }, template: 'Det här är det {{bästa}} valet.' },
    { id: 'b5_phrase_trottare_an_jag', kind: 'phrase_fill', concept: 'trottare_an_jag', lemma: 'tröttare', source: 'phrase', prompt: { zh: '她比我更累。' }, template: 'Hon är {{tröttare}} än jag.' },
    { id: 'b5_phrase_battre_bast', kind: 'phrase_fill', concept: 'battre_bast', lemma: 'bättre bäst', source: 'phrase', prompt: { zh: '好 → 更好 → 最好' }, template: 'bra → {{bättre}} → {{bäst}}' },
    { id: 'b5_phrase_samre_samst', kind: 'phrase_fill', concept: 'samre_samst', lemma: 'sämre sämst', source: 'phrase', prompt: { zh: '差 → 更差 → 最差' }, template: 'dålig → {{sämre}} → {{sämst}}' },
    { id: 'b5_phrase_yngre_yngst', kind: 'phrase_fill', concept: 'yngre_yngst', lemma: 'yngre yngst', source: 'phrase', prompt: { zh: '年轻 → 更年轻 → 最年轻' }, template: 'ung → {{yngre}} → {{yngst}}' },
    { id: 'b5_phrase_aldre_aldst', kind: 'phrase_fill', concept: 'aldre_aldst', lemma: 'äldre äldst', source: 'phrase', prompt: { zh: '老 → 更老 → 最老' }, template: 'gammal → {{äldre}} → {{äldst}}' },
    { id: 'b5_phrase_mindre_minst', kind: 'phrase_fill', concept: 'mindre_minst', lemma: 'mindre minst', source: 'phrase', prompt: { zh: '小 → 更小 → 最小' }, template: 'liten → {{mindre}} → {{minst}}' },
    { id: 'b5_phrase_stor_och_ljus_lagenhet', kind: 'phrase_fill', concept: 'stor_och_ljus_lagenhet', lemma: 'stor ljus', source: 'phrase', prompt: { zh: '他们有一套大而明亮的公寓。' }, template: 'De har en {{stor}} och {{ljus}} lägenhet.' },
    { id: 'b5_phrase_nyare_och_lattare', kind: 'phrase_fill', concept: 'nyare_och_lattare', lemma: 'nyare lättare', source: 'phrase', prompt: { zh: '蓝色的自行车更新也更轻。' }, template: 'Den blå cykeln är {{nyare}} och {{lättare}}.' },
    { id: 'b5_phrase_ett_nytt_bord', kind: 'phrase_fill', concept: 'ett_nytt_bord', lemma: 'nytt', source: 'phrase', prompt: { zh: '我想要一张新桌子和舒适的椅子。' }, template: 'Jag vill ha ett {{nytt}} bord och bekväma stolar.' },
    { id: 'b5_phrase_det_basta_valet', kind: 'phrase_fill', concept: 'det_basta_valet', lemma: 'bästa', source: 'phrase', prompt: { zh: '这看起来是最好的选择。' }, template: 'Det verkar vara det {{bästa}} valet.' },
    { id: 'b5_phrase_lite_dyrare', kind: 'phrase_fill', concept: 'lite_dyrare', lemma: 'dyrare', source: 'phrase', prompt: { zh: '租金稍微更贵一点，但还合理。' }, template: 'Hyran är lite {{dyrare}} men rimlig.' },
    // ===== 对话句题 =====
    { id: 'b5_dialog_hur_ar_din_nya_lagenhet', kind: 'dialog_fill', concept: 'hur_ar_din_nya_lagenhet', lemma: 'lägenhet', source: 'dialog', prompt: { zh: '你的新公寓怎么样？' }, template: 'Hur är din nya {{lägenhet}}?' },
    { id: 'b5_dialog_den_ar_stor_och_ljus', kind: 'dialog_fill', concept: 'den_ar_stor_och_ljus', lemma: 'ljus', source: 'dialog', prompt: { zh: '它很大也很明亮！' }, template: 'Den är stor och {{ljus}}!' },
    { id: 'b5_dialog_rummen_ar_storre', kind: 'dialog_fill', concept: 'rummen_ar_storre', lemma: 'större', source: 'dialog', prompt: { zh: '这些房间比我旧公寓里的更大。' }, template: 'Rummen är {{större}} än i min gamla lägenhet.' },
    { id: 'b5_dialog_ar_det_dyrt', kind: 'dialog_fill', concept: 'ar_det_dyrt', lemma: 'dyrt', source: 'dialog', prompt: { zh: '贵吗？' }, template: 'Är det {{dyrt}}?' },
    { id: 'b5_dialog_lite_dyrare_men_rimlig', kind: 'dialog_fill', concept: 'lite_dyrare_men_rimlig', lemma: 'dyrare', source: 'dialog', prompt: { zh: '稍微更贵一点，但租金合理。' }, template: 'Lite {{dyrare}} men hyran är rimlig.' },
    { id: 'b5_dialog_det_basta_laget', kind: 'dialog_fill', concept: 'det_basta_laget', lemma: 'bästa', source: 'dialog', prompt: { zh: '而且这里的位置是最好的——离地铁很近！' }, template: 'Och det är det {{bästa}} läget – nära tunnelbanan!' },
    { id: 'b5_dialog_har_du_egna_mobler', kind: 'dialog_fill', concept: 'har_du_egna_mobler', lemma: 'möbler', source: 'dialog', prompt: { zh: '你有自己的家具，还是需要买新的？' }, template: 'Har du egna {{möbler}} eller behöver du köpa nya?' },
    { id: 'b5_dialog_ett_nytt_bord_och_bekvama_stolar', kind: 'dialog_fill', concept: 'ett_nytt_bord_och_bekvama_stolar', lemma: 'nytt', source: 'dialog', prompt: { zh: '我有一些旧家具，但我想要一张新桌子和舒适的椅子。' }, template: 'Jag har några gamla möbler men jag vill ha ett {{nytt}} bord och bekväma stolar.' },
    { id: 'b5_dialog_vilken_cykel_ar_billigast', kind: 'dialog_fill', concept: 'vilken_cykel_ar_billigast', lemma: 'cykel billigast', source: 'dialog', prompt: { zh: '哪辆自行车最便宜？' }, template: 'Vilken {{cykel}} är billigast?' },
    { id: 'b5_dialog_den_roda_ar_billigare', kind: 'dialog_fill', concept: 'den_roda_ar_billigare', lemma: 'billigare', source: 'dialog', prompt: { zh: '红色那辆比蓝色那辆更便宜，但蓝色那辆状态更好。' }, template: 'Den röda är {{billigare}} än den blå, men den blå är i bättre skick.' },
    { id: 'b5_dialog_ar_den_roda_valdigt_gammal', kind: 'dialog_fill', concept: 'ar_den_roda_valdigt_gammal', lemma: 'gammal', source: 'dialog', prompt: { zh: '红色那辆很旧吗？' }, template: 'Är den röda väldigt {{gammal}}?' },
    { id: 'b5_dialog_den_ar_aldre', kind: 'dialog_fill', concept: 'den_ar_aldre', lemma: 'äldre', source: 'dialog', prompt: { zh: '它更旧一些，但很好用。' }, template: 'Den är {{äldre}} men fungerar bra.' },
    { id: 'b5_dialog_den_bla_ar_nyare_och_lattare', kind: 'dialog_fill', concept: 'den_bla_ar_nyare_och_lattare', lemma: 'nyare lättare', source: 'dialog', prompt: { zh: '蓝色那辆更新也更轻。' }, template: 'Den blå är {{nyare}} och {{lättare}}.' },
    { id: 'b5_dialog_jag_tar_den_bla', kind: 'dialog_fill', concept: 'jag_tar_den_bla', lemma: 'tar', source: 'dialog', prompt: { zh: '我选蓝色那辆。' }, template: 'Jag tar den blå.' },
    { id: 'b5_dialog_det_verkar_vara_det_basta_valet', kind: 'dialog_fill', concept: 'det_verkar_vara_det_basta_valet', lemma: 'bästa', source: 'dialog', prompt: { zh: '这看起来是最好的选择。' }, template: 'Det verkar vara det {{bästa}} valet.' }
  ],
  advancedPool: [
    // ===== adjective_forms =====
    { id: 'b5_adj_stor_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'stor', prompt: { zh: '大的' }, template: '{{stor}} | {{stort}} | {{stora}}' },
    { id: 'b5_adj_ny_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'ny', prompt: { zh: '新的' }, template: '{{ny}} | {{nytt}} | {{nya}}' },
    { id: 'b5_adj_gammal_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'gammal', prompt: { zh: '旧的 / 老的' }, template: '{{gammal}} | {{gammalt}} | {{gamla}}' },
    { id: 'b5_adj_bra_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'bra', prompt: { zh: '好的' }, template: '{{bra}} | {{bra}} | {{bra}}', autoPlay: false },
    { id: 'b5_adj_dalig_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'dålig', prompt: { zh: '差的 / 坏的' }, template: '{{dålig}} | {{dåligt}} | {{dåliga}}' },
    { id: 'b5_adj_billig_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'billig', prompt: { zh: '便宜的' }, template: '{{billig}} | {{billigt}} | {{billiga}}' },
    { id: 'b5_adj_dyr_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'dyr', prompt: { zh: '贵的' }, template: '{{dyr}} | {{dyrt}} | {{dyra}}' },
    { id: 'b5_adj_snabb_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'snabb', prompt: { zh: '快的' }, template: '{{snabb}} | {{snabbt}} | {{snabba}}' },
    { id: 'b5_adj_langsam_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'långsam', prompt: { zh: '慢的' }, template: '{{långsam}} | {{långsamt}} | {{långsamma}}' },
    { id: 'b5_adj_varm_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'varm', prompt: { zh: '热的 / 温暖的' }, template: '{{varm}} | {{varmt}} | {{varma}}' },
    { id: 'b5_adj_kall_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'kall', prompt: { zh: '冷的' }, template: '{{kall}} | {{kallt}} | {{kalla}}' },
    { id: 'b5_adj_latt_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'lätt', prompt: { zh: '轻的 / 容易的' }, template: '{{lätt}} | {{lätt}} | {{lätta}}' },
    { id: 'b5_adj_svar_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'svår', prompt: { zh: '难的 / 重的' }, template: '{{svår}} | {{svårt}} | {{svåra}}' },
    { id: 'b5_adj_ung_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'ung', prompt: { zh: '年轻的' }, template: '{{ung}} | {{ungt}} | {{unga}}' },
    { id: 'b5_adj_trott_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'trött', prompt: { zh: '累的' }, template: '{{trött}} | {{trött}} | {{trötta}}' },
    { id: 'b5_adj_glad_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'glad', prompt: { zh: '高兴的' }, template: '{{glad}} | {{glatt}} | {{glada}}' },
    { id: 'b5_adj_ledsen_group', kind: 'morphology', source: 'adjective', labelScheme: 'adjective_forms', slotLabels: ['en-词形式', 'ett-词形式', '复数 / 定指形式'], lemma: 'ledsen', prompt: { zh: '伤心的 / 抱歉的' }, template: '{{ledsen}} | {{ledset}} | {{ledsna}}' },
    // ===== comparison_forms =====
    { id: 'b5_comp_stor_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'stor', prompt: { zh: '大的 → 更大的 → 最大的' }, template: '{{stor}} | {{större}} | {{störst}}' },
    { id: 'b5_comp_liten_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'liten', prompt: { zh: '小的 → 更小的 → 最小的' }, template: '{{liten}} | {{mindre}} | {{minst}}' },
    { id: 'b5_comp_ny_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'ny', prompt: { zh: '新的 → 更新的 → 最新的' }, template: '{{ny}} | {{nyare}} | {{nyast}}' },
    { id: 'b5_comp_gammal_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'gammal', prompt: { zh: '旧的 / 老的 → 更旧的 / 更老的 → 最旧的 / 最老的' }, template: '{{gammal}} | {{äldre}} | {{äldst}}' },
    { id: 'b5_comp_bra_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'bra', prompt: { zh: '好的 → 更好的 → 最好的' }, template: '{{bra}} | {{bättre}} | {{bäst}}' },
    { id: 'b5_comp_dalig_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'dålig', prompt: { zh: '差的 / 坏的 → 更差的 / 更坏的 → 最差的 / 最坏的' }, template: '{{dålig}} | {{sämre}} | {{sämst}}' },
    { id: 'b5_comp_billig_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'billig', prompt: { zh: '便宜的 → 更便宜的 → 最便宜的' }, template: '{{billig}} | {{billigare}} | {{billigast}}' },
    { id: 'b5_comp_dyr_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'dyr', prompt: { zh: '贵的 → 更贵的 → 最贵的' }, template: '{{dyr}} | {{dyrare}} | {{dyrast}}' },
    { id: 'b5_comp_snabb_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'snabb', prompt: { zh: '快的 → 更快的 → 最快的' }, template: '{{snabb}} | {{snabbare}} | {{snabbast}}' },
    { id: 'b5_comp_langsam_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'långsam', prompt: { zh: '慢的 → 更慢的 → 最慢的' }, template: '{{långsam}} | {{långsammare}} | {{långsammast}}' },
    { id: 'b5_comp_varm_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'varm', prompt: { zh: '热的 / 温暖的 → 更热的 / 更温暖的 → 最热的 / 最温暖的' }, template: '{{varm}} | {{varmare}} | {{varmast}}' },
    { id: 'b5_comp_kall_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'kall', prompt: { zh: '冷的 → 更冷的 → 最冷的' }, template: '{{kall}} | {{kallare}} | {{kallast}}' },
    { id: 'b5_comp_latt_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'lätt', prompt: { zh: '轻的 / 容易的 → 更轻的 / 更容易的 → 最轻的 / 最容易的' }, template: '{{lätt}} | {{lättare}} | {{lättast}}' },
    { id: 'b5_comp_svar_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'svår', prompt: { zh: '难的 / 重的 → 更难的 / 更重的 → 最难的 / 最重的' }, template: '{{svår}} | {{svårare}} | {{svårast}}' },
    { id: 'b5_comp_ung_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'ung', prompt: { zh: '年轻的 → 更年轻的 → 最年轻的' }, template: '{{ung}} | {{yngre}} | {{yngst}}' },
    { id: 'b5_comp_trott_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'trött', prompt: { zh: '累的 → 更累的 → 最累的' }, template: '{{trött}} | {{tröttare}} | {{tröttast}}' },
    { id: 'b5_comp_glad_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'glad', prompt: { zh: '高兴的 → 更高兴的 → 最高兴的' }, template: '{{glad}} | {{gladare}} | {{gladast}}' },
    { id: 'b5_comp_ledsen_group', kind: 'morphology', source: 'comparison', slotLabels: ['原级', '比较级', '最高级'], lemma: 'ledsen', prompt: { zh: '伤心的 / 抱歉的 → 更伤心的 / 更抱歉的 → 最伤心的 / 最抱歉的' }, template: '{{ledsen}} | {{ledsnare}} | {{ledsnast}}' },
    // ===== noun_forms =====
    { id: 'b5_noun_lagenhet_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'lägenhet', prompt: { zh: '公寓' }, template: '{{en}} | {{lägenhet}} | {{lägenheten}} | {{lägenheter}} | {{lägenheterna}}' },
    { id: 'b5_noun_rum_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'rum', prompt: { zh: '房间' }, template: '{{ett}} | {{rum}} | {{rummet}} | {{rum}} | {{rummen}}' },
    { id: 'b5_noun_hyra_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'hyra', prompt: { zh: '租金' }, template: '{{en}} | {{hyra}} | {{hyran}} | {{hyror}} | {{hyrorna}}' },
    { id: 'b5_noun_val_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'val', prompt: { zh: '选择' }, template: '{{ett}} | {{val}} | {{valet}} | {{val}} | {{valen}}' },
    { id: 'b5_noun_cykel_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'cykel', prompt: { zh: '自行车' }, template: '{{en}} | {{cykel}} | {{cykeln}} | {{cyklar}} | {{cyklarna}}' },
    { id: 'b5_noun_skick_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'skick', prompt: { zh: '状态 / 状况' }, template: '{{ett}} | {{skick}} | {{skicket}} | {{skick}} | {{skicken}}' },
    // ===== verb_forms =====
    { id: 'b5_verb_verka_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'verka', prompt: { zh: '似乎 / 好像' }, template: '{{verka}} | {{verkar}} | {{verkade}} | {{verkat}}' },
    { id: 'b5_verb_behova_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'behöva', prompt: { zh: '需要' }, template: '{{behöva}} | {{behöver}} | {{behövde}} | {{behövt}}' },
    { id: 'b5_verb_jamfora_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'jämföra', prompt: { zh: '比较' }, template: '{{jämföra}} | {{jämför}} | {{jämförde}} | {{jämfört}}' },
    { id: 'b5_verb_valja_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'välja', prompt: { zh: '选择 / 选' }, template: '{{välja}} | {{väljer}} | {{valde}} | {{valt}}' }
  ]
};
