window.UNIT_BANK_C1 = {
  unit: 'c1',
  unitTitle: '过去时',
  basicPool: [
    // ===== 单词题 =====
    { id: 'c1_vocab_ga', kind: 'vocab_spelling', concept: 'gå', lemma: 'gå', source: 'vocab', prompt: { zh: '去 / 走（动词原形）' }, answer: 'gå' },
    { id: 'c1_vocab_ata', kind: 'vocab_spelling', concept: 'äta', lemma: 'äta', source: 'vocab', prompt: { zh: '吃（动词原形）' }, answer: 'äta' },
    { id: 'c1_vocab_komma', kind: 'vocab_spelling', concept: 'komma', lemma: 'komma', source: 'vocab', prompt: { zh: '来（动词原形）' }, answer: 'komma' },
    { id: 'c1_vocab_dricka', kind: 'vocab_spelling', concept: 'dricka', lemma: 'dricka', source: 'vocab', prompt: { zh: '喝（动词原形）' }, answer: 'dricka' },
    { id: 'c1_vocab_fa', kind: 'vocab_spelling', concept: 'få', lemma: 'få', source: 'vocab', prompt: { zh: '得到 / 收到（动词原形）' }, answer: 'få' },
    { id: 'c1_vocab_lasa', kind: 'vocab_spelling', concept: 'läsa', lemma: 'läsa', source: 'vocab', prompt: { zh: '阅读（动词原形）' }, answer: 'läsa' },
    { id: 'c1_vocab_glomma', kind: 'vocab_spelling', concept: 'glömma', lemma: 'glömma', source: 'vocab', prompt: { zh: '忘记（动词原形）' }, answer: 'glömma' },
    { id: 'c1_vocab_stanna', kind: 'vocab_spelling', concept: 'stanna', lemma: 'stanna', source: 'vocab', prompt: { zh: '停留 / 留下（动词原形）' }, answer: 'stanna' },
    { id: 'c1_vocab_diskutera', kind: 'vocab_spelling', concept: 'diskutera', lemma: 'diskutera', source: 'vocab', prompt: { zh: '讨论（动词原形）' }, answer: 'diskutera' },
    { id: 'c1_vocab_presentera', kind: 'vocab_spelling', concept: 'presentera', lemma: 'presentera', source: 'vocab', prompt: { zh: '介绍 / 展示（动词原形）' }, answer: 'presentera' },
    { id: 'c1_vocab_tycka', kind: 'vocab_spelling', concept: 'tycka', lemma: 'tycka', source: 'vocab', prompt: { zh: '觉得 / 认为（动词原形）' }, answer: 'tycka' },
    { id: 'c1_vocab_bestamma', kind: 'vocab_spelling', concept: 'bestämma', lemma: 'bestämma', source: 'vocab', prompt: { zh: '决定（动词原形）' }, answer: 'bestämma' },
    { id: 'c1_vocab_starta', kind: 'vocab_spelling', concept: 'starta', lemma: 'starta', source: 'vocab', prompt: { zh: '开始（动词原形）' }, answer: 'starta' },
    { id: 'c1_vocab_skicka', kind: 'vocab_spelling', concept: 'skicka', lemma: 'skicka', source: 'vocab', prompt: { zh: '发送（动词原形）' }, answer: 'skicka' },
    { id: 'c1_vocab_prata', kind: 'vocab_spelling', concept: 'prata', lemma: 'prata', source: 'vocab', prompt: { zh: '说话 / 谈话（动词原形）' }, answer: 'prata' },
    { id: 'c1_vocab_komma_ihag', kind: 'vocab_spelling', concept: 'komma ihåg', lemma: 'komma ihåg', source: 'vocab', prompt: { zh: '记得 / 想起（动词原形）' }, answer: 'komma ihåg' },
    { id: 'c1_vocab_handa', kind: 'vocab_spelling', concept: 'hända', lemma: 'hända', source: 'vocab', prompt: { zh: '发生（动词原形）' }, answer: 'hända' },
    { id: 'c1_vocab_besoka', kind: 'vocab_spelling', concept: 'besöka', lemma: 'besöka', source: 'vocab', prompt: { zh: '拜访 / 参观（动词原形）' }, answer: 'besöka' },
    { id: 'c1_vocab_traffa', kind: 'vocab_spelling', concept: 'träffa', lemma: 'träffa', source: 'vocab', prompt: { zh: '遇见（动词原形）' }, answer: 'träffa' },
    { id: 'c1_vocab_aka', kind: 'vocab_spelling', concept: 'åka', lemma: 'åka', source: 'vocab', prompt: { zh: '旅行 / 去（动词原形）' }, answer: 'åka' },
    { id: 'c1_vocab_helg', kind: 'vocab_spelling', concept: 'helg', lemma: 'helg', source: 'vocab', prompt: { zh: '周末（名词，单数）' }, answer: 'en helg' },
    { id: 'c1_vocab_familj', kind: 'vocab_spelling', concept: 'familj', lemma: 'familj', source: 'vocab', prompt: { zh: '家庭（名词，单数）' }, answer: 'en familj' },
    { id: 'c1_vocab_hotell', kind: 'vocab_spelling', concept: 'hotell', lemma: 'hotell', source: 'vocab', prompt: { zh: '酒店（名词，单数）' }, answer: 'ett hotell' },
    { id: 'c1_vocab_hamn', kind: 'vocab_spelling', concept: 'hamn', lemma: 'hamn', source: 'vocab', prompt: { zh: '港口（名词，单数）' }, answer: 'en hamn' },
    { id: 'c1_vocab_van', kind: 'vocab_spelling', concept: 'vän', lemma: 'vän', source: 'vocab', prompt: { zh: '朋友（名词，单数）' }, answer: 'en vän' },
    { id: 'c1_vocab_skola', kind: 'vocab_spelling', concept: 'skola', lemma: 'skola', source: 'vocab', prompt: { zh: '学校（名词，单数）' }, answer: 'en skola' },
    { id: 'c1_vocab_mote', kind: 'vocab_spelling', concept: 'möte', lemma: 'möte', source: 'vocab', prompt: { zh: '会议（名词，单数）' }, answer: 'ett möte' },
    { id: 'c1_vocab_projekt', kind: 'vocab_spelling', concept: 'projekt', lemma: 'projekt', source: 'vocab', prompt: { zh: '项目（名词，单数）' }, answer: 'ett projekt' },
    { id: 'c1_vocab_chef', kind: 'vocab_spelling', concept: 'chef', lemma: 'chef', source: 'vocab', prompt: { zh: '老板（名词，单数）' }, answer: 'en chef' },
    { id: 'c1_vocab_plan', kind: 'vocab_spelling', concept: 'plan', lemma: 'plan', source: 'vocab', prompt: { zh: '计划（名词，单数）' }, answer: 'en plan' },
    { id: 'c1_vocab_manad', kind: 'vocab_spelling', concept: 'månad', lemma: 'månad', source: 'vocab', prompt: { zh: '月（名词，单数）' }, answer: 'en månad' },
    { id: 'c1_vocab_mejl', kind: 'vocab_spelling', concept: 'mejl', lemma: 'mejl', source: 'vocab', prompt: { zh: '邮件（名词，单数）' }, answer: 'ett mejl' },
    { id: 'c1_vocab_information', kind: 'vocab_spelling', concept: 'information', lemma: 'information', source: 'vocab', prompt: { zh: '信息（名词，单数）' }, answer: 'en information' },
    { id: 'c1_vocab_mage', kind: 'vocab_spelling', concept: 'mage', lemma: 'mage', source: 'vocab', prompt: { zh: '肚子 / 胃（名词，单数）' }, answer: 'en mage' },
    // ===== 固定表达题 =====
    { id: 'c1_phrase_jag_akte_till_goteborg', kind: 'phrase_fill', concept: 'jag_akte_till_goteborg', lemma: 'åkte', source: 'phrase', prompt: { zh: '我周末去了哥德堡。' }, template: 'Jag {{åkte}} till Göteborg i helgen.' },
    { id: 'c1_phrase_vi_bodde_pa_hotell', kind: 'phrase_fill', concept: 'vi_bodde_pa_hotell', lemma: 'bodde', source: 'phrase', prompt: { zh: '我们住在酒店。' }, template: 'Vi {{bodde}} på hotell.' },
    { id: 'c1_phrase_vi_at_fisk_och_rakor', kind: 'phrase_fill', concept: 'vi_at_fisk_och_rakor', lemma: 'åt', source: 'phrase', prompt: { zh: '我们吃了鱼和虾。' }, template: 'Vi {{åt}} fisk och räkor.' },
    { id: 'c1_phrase_barnen_drack_saft', kind: 'phrase_fill', concept: 'barnen_drack_saft', lemma: 'drack', source: 'phrase', prompt: { zh: '孩子们喝了果汁。' }, template: 'Barnen {{drack}} saft.' },
    { id: 'c1_phrase_vi_traffade_gamla_vanner', kind: 'phrase_fill', concept: 'vi_traffade_gamla_vanner', lemma: 'träffade', source: 'phrase', prompt: { zh: '我们遇见了老朋友。' }, template: 'Vi {{träffade}} gamla vänner.' },
    { id: 'c1_phrase_du_var_inte_pa_motet', kind: 'phrase_fill', concept: 'du_var_inte_pa_motet', lemma: 'var', source: 'phrase', prompt: { zh: '你昨天不在会议上。' }, template: 'Du {{var}} inte på mötet igår.' },
    { id: 'c1_phrase_vad_hande', kind: 'phrase_fill', concept: 'vad_hande', lemma: 'hände', source: 'phrase', prompt: { zh: '发生了什么？' }, template: 'Vad {{hände}}?' },
    { id: 'c1_phrase_jag_fick_mejlet', kind: 'phrase_fill', concept: 'jag_fick_mejlet', lemma: 'fick', source: 'phrase', prompt: { zh: '我收到了邮件。' }, template: 'Jag {{fick}} mejlet.' },
    { id: 'c1_phrase_jag_laste_det_just', kind: 'phrase_fill', concept: 'jag_laste_det_just', lemma: 'läste', source: 'phrase', prompt: { zh: '我刚刚读了它。' }, template: 'Jag {{läste}} det just.' },
    { id: 'c1_phrase_jag_glomde_det', kind: 'phrase_fill', concept: 'jag_glomde_det', lemma: 'glömde', source: 'phrase', prompt: { zh: '我忘了。' }, template: 'Jag {{glömde}} det.' },
    { id: 'c1_phrase_jag_hade_ont_i_magen', kind: 'phrase_fill', concept: 'jag_hade_ont_i_magen', lemma: 'hade', source: 'phrase', prompt: { zh: '我肚子疼。' }, template: 'Jag {{hade}} ont i magen.' },
    { id: 'c1_phrase_jag_stannade_hemma', kind: 'phrase_fill', concept: 'jag_stannade_hemma', lemma: 'stannade', source: 'phrase', prompt: { zh: '我待在家里。' }, template: 'Jag {{stannade}} hemma.' },
    { id: 'c1_phrase_vi_diskuterade_det_nya_projektet', kind: 'phrase_fill', concept: 'vi_diskuterade_det_nya_projektet', lemma: 'diskuterade', source: 'phrase', prompt: { zh: '我们讨论了新项目。' }, template: 'Vi {{diskuterade}} det nya projektet.' },
    { id: 'c1_phrase_chefen_presenterade_planen', kind: 'phrase_fill', concept: 'chefen_presenterade_planen', lemma: 'presenterade', source: 'phrase', prompt: { zh: '老板介绍了计划。' }, template: 'Chefen {{presenterade}} planen.' },
    { id: 'c1_phrase_alla_tyckte_att_det_lat_bra', kind: 'phrase_fill', concept: 'alla_tyckte_att_det_lat_bra', lemma: 'tyckte', source: 'phrase', prompt: { zh: '大家都觉得这听起来不错。' }, template: 'Alla {{tyckte}} att det lät bra.' },
    { id: 'c1_phrase_vi_bestamde_att_starta', kind: 'phrase_fill', concept: 'vi_bestamde_att_starta', lemma: 'bestämde', source: 'phrase', prompt: { zh: '我们决定下个月启动项目。' }, template: 'Vi {{bestämde}} att starta projektet nästa månad.' },
    { id: 'c1_phrase_jag_skickade_ett_mejl', kind: 'phrase_fill', concept: 'jag_skickade_ett_mejl', lemma: 'skickade', source: 'phrase', prompt: { zh: '我发了一封带所有信息的邮件。' }, template: 'Jag {{skickade}} ett mejl med all information.' },
    { id: 'c1_phrase_vad_gjorde_du_i_helgen', kind: 'phrase_fill', concept: 'vad_gjorde_du_i_helgen', lemma: 'gjorde', source: 'phrase', prompt: { zh: '你周末做了什么？' }, template: 'Vad {{gjorde}} du i helgen?' },
    { id: 'c1_phrase_at_ni_nagot_speciellt', kind: 'phrase_fill', concept: 'at_ni_nagot_speciellt', lemma: 'åt', source: 'phrase', prompt: { zh: '你们吃了什么特别的东西吗？' }, template: '{{Åt}} ni något speciellt?' },
    { id: 'c1_phrase_bestamde_ni_nagot', kind: 'phrase_fill', concept: 'bestamde_ni_nagot', lemma: 'bestämde', source: 'phrase', prompt: { zh: '你们决定了什么吗？' }, template: '{{Bestämde}} ni något?' },
    { id: 'c1_phrase_fick_du_det', kind: 'phrase_fill', concept: 'fick_du_det', lemma: 'fick', source: 'phrase', prompt: { zh: '你收到邮件了吗？' }, template: '{{Fick}} du det?' },
    // ===== 对话句题 =====
    { id: 'c1_dialog_vad_gjorde_du_i_helgen', kind: 'dialog_fill', concept: 'vad_gjorde_du_i_helgen_dialog', lemma: 'gjorde', source: 'dialog', prompt: { zh: '你周末做了什么？' }, template: 'Vad {{gjorde}} du i helgen?' },
    { id: 'c1_dialog_jag_akte_till_goteborg_med_familjen', kind: 'dialog_fill', concept: 'jag_akte_till_goteborg_med_familjen', lemma: 'åkte', source: 'dialog', prompt: { zh: '我跟家人去了哥德堡。' }, template: 'Jag {{åkte}} till Göteborg med familjen.' },
    { id: 'c1_dialog_vi_bodde_pa_hotell_och_besokte_liseberg', kind: 'dialog_fill', concept: 'vi_bodde_pa_hotell_och_besokte_liseberg', lemma: 'bodde besökte', source: 'dialog', prompt: { zh: '我们住在酒店，也去了里瑟本游乐园。' }, template: 'Vi {{bodde}} på hotell och {{besökte}} Liseberg.' },
    { id: 'c1_dialog_at_ni_nagot_speciellt_dialog', kind: 'dialog_fill', concept: 'at_ni_nagot_speciellt_dialog', lemma: 'åt', source: 'dialog', prompt: { zh: '你们吃了什么特别的吗？' }, template: '{{Åt}} ni något speciellt?' },
    { id: 'c1_dialog_vi_at_fisk_och_rakor_vid_hamnen', kind: 'dialog_fill', concept: 'vi_at_fisk_och_rakor_vid_hamnen', lemma: 'åt', source: 'dialog', prompt: { zh: '我们在港口吃了鱼和虾。' }, template: 'Vi {{åt}} fisk och räkor vid hamnen.' },
    { id: 'c1_dialog_barnen_drack_saft_och_vi_vuxna_drack_vin', kind: 'dialog_fill', concept: 'barnen_drack_saft_och_vi_vuxna_drack_vin', lemma: 'drack', source: 'dialog', prompt: { zh: '孩子们喝果汁，大人喝酒。' }, template: 'Barnen {{drack}} saft och vi vuxna drack vin.' },
    { id: 'c1_dialog_traffade_ni_nagra_gamla_vanner', kind: 'dialog_fill', concept: 'traffade_ni_nagra_gamla_vanner', lemma: 'träffade', source: 'dialog', prompt: { zh: '你们见到老朋友了吗？' }, template: '{{Träffade}} ni några gamla vänner?' },
    { id: 'c1_dialog_vi_pratade_i_flera_timmar', kind: 'dialog_fill', concept: 'vi_pratade_i_flera_timmar', lemma: 'pratade', source: 'dialog', prompt: { zh: '我们和以前的同学聊了好几个小时。' }, template: 'Vi {{pratade}} i flera timmar.' },
    { id: 'c1_dialog_vi_kom_ihag_massa_saker', kind: 'dialog_fill', concept: 'vi_kom_ihag_massa_saker', lemma: 'kom ihåg', source: 'dialog', prompt: { zh: '我们想起了很多学校里的事情。' }, template: 'Vi {{kom ihåg}} massa saker från skolan.' },
    { id: 'c1_dialog_du_var_inte_pa_motet_igar', kind: 'dialog_fill', concept: 'du_var_inte_pa_motet_igar', lemma: 'var hände', source: 'dialog', prompt: { zh: '你昨天没来开会。发生了什么？' }, template: 'Du {{var}} inte på mötet igår. Vad {{hände}}?' },
    { id: 'c1_dialog_forlat_jag_glomde_det', kind: 'dialog_fill', concept: 'forlat_jag_glomde_det', lemma: 'glömde', source: 'dialog', prompt: { zh: '对不起，我忘了。' }, template: 'Förlåt, jag {{glömde}} det.' },
    { id: 'c1_dialog_jag_hade_ont_i_magen_och_stannade_hemma', kind: 'dialog_fill', concept: 'jag_hade_ont_i_magen_och_stannade_hemma', lemma: 'hade stannade', source: 'dialog', prompt: { zh: '我肚子疼，所以待在家里。' }, template: 'Jag {{hade}} ont i magen och {{stannade}} hemma.' },
    { id: 'c1_dialog_vi_diskuterade_det_nya_projektet', kind: 'dialog_fill', concept: 'vi_diskuterade_det_nya_projektet_dialog', lemma: 'diskuterade', source: 'dialog', prompt: { zh: '我们讨论了新项目。' }, template: 'Vi {{diskuterade}} det nya projektet.' },
    { id: 'c1_dialog_chefen_presenterade_planen', kind: 'dialog_fill', concept: 'chefen_presenterade_planen_dialog', lemma: 'presenterade', source: 'dialog', prompt: { zh: '老板介绍了计划。' }, template: 'Chefen {{presenterade}} planen.' },
    { id: 'c1_dialog_alla_tyckte_att_det_lat_bra', kind: 'dialog_fill', concept: 'alla_tyckte_att_det_lat_bra_dialog', lemma: 'tyckte', source: 'dialog', prompt: { zh: '大家都觉得听起来不错。' }, template: 'Alla {{tyckte}} att det lät bra.' },
    { id: 'c1_dialog_bestamde_ni_nagot_dialog', kind: 'dialog_fill', concept: 'bestamde_ni_nagot_dialog', lemma: 'bestämde', source: 'dialog', prompt: { zh: '你们决定了什么吗？' }, template: '{{Bestämde}} ni något?' },
    { id: 'c1_dialog_vi_bestamde_att_starta_projektet', kind: 'dialog_fill', concept: 'vi_bestamde_att_starta_projektet', lemma: 'bestämde', source: 'dialog', prompt: { zh: '我们决定下个月启动项目。' }, template: 'Vi {{bestämde}} att starta projektet nästa månad.' },
    { id: 'c1_dialog_jag_skickade_ett_mejl_med_all_information', kind: 'dialog_fill', concept: 'jag_skickade_ett_mejl_med_all_information', lemma: 'skickade', source: 'dialog', prompt: { zh: '我给你发了一封包含所有信息的邮件。' }, template: 'Jag {{skickade}} ett mejl med all information.' },
    { id: 'c1_dialog_fick_du_det', kind: 'dialog_fill', concept: 'fick_du_det_dialog', lemma: 'fick', source: 'dialog', prompt: { zh: '你收到那封邮件了吗？' }, template: '{{Fick}} du det?' },
    { id: 'c1_dialog_jag_laste_det_just', kind: 'dialog_fill', concept: 'jag_laste_det_just_dialog', lemma: 'läste', source: 'dialog', prompt: { zh: '我刚刚读完。' }, template: 'Jag {{läste}} det just.' },
    { id: 'c1_dialog_det_verkade_intressant', kind: 'dialog_fill', concept: 'det_verkade_intressant', lemma: 'verkade', source: 'dialog', prompt: { zh: '它看起来很有意思。' }, template: 'Det {{verkade}} intressant.' }
  ],
  advancedPool: [
    // ===== verb_forms =====
    { id: 'c1_verb_vara_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'vara', prompt: { zh: '是' }, template: '{{vara}} | {{är}} | {{var}} | {{varit}}' },
    { id: 'c1_verb_ga_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'gå', prompt: { zh: '去 / 走' }, template: '{{gå}} | {{går}} | {{gick}} | {{gått}}' },
    { id: 'c1_verb_ata_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'äta', prompt: { zh: '吃' }, template: '{{äta}} | {{äter}} | {{åt}} | {{ätit}}' },
    { id: 'c1_verb_komma_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'komma', prompt: { zh: '来' }, template: '{{komma}} | {{kommer}} | {{kom}} | {{kommit}}' },
    { id: 'c1_verb_dricka_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'dricka', prompt: { zh: '喝' }, template: '{{dricka}} | {{dricker}} | {{drack}} | {{druckit}}' },
    { id: 'c1_verb_fa_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'få', prompt: { zh: '得到 / 收到' }, template: '{{få}} | {{får}} | {{fick}} | {{fått}}' },
    { id: 'c1_verb_lasa_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'läsa', prompt: { zh: '阅读' }, template: '{{läsa}} | {{läser}} | {{läste}} | {{läst}}' },
    { id: 'c1_verb_gora_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'göra', prompt: { zh: '做' }, template: '{{göra}} | {{gör}} | {{gjorde}} | {{gjort}}' },
    { id: 'c1_verb_glomma_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'glömma', prompt: { zh: '忘记' }, template: '{{glömma}} | {{glömmer}} | {{glömde}} | {{glömt}}' },
    { id: 'c1_verb_stanna_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'stanna', prompt: { zh: '停留 / 留下' }, template: '{{stanna}} | {{stannar}} | {{stannade}} | {{stannat}}' },
    { id: 'c1_verb_diskutera_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'diskutera', prompt: { zh: '讨论' }, template: '{{diskutera}} | {{diskuterar}} | {{diskuterade}} | {{diskuterat}}' },
    { id: 'c1_verb_presentera_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'presentera', prompt: { zh: '介绍 / 展示' }, template: '{{presentera}} | {{presenterar}} | {{presenterade}} | {{presenterat}}' },
    { id: 'c1_verb_tycka_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'tycka', prompt: { zh: '觉得 / 认为' }, template: '{{tycka}} | {{tycker}} | {{tyckte}} | {{tyckt}}' },
    { id: 'c1_verb_bestamma_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'bestämma', prompt: { zh: '决定' }, template: '{{bestämma}} | {{bestämmer}} | {{bestämde}} | {{bestämt}}' },
    { id: 'c1_verb_starta_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'starta', prompt: { zh: '开始' }, template: '{{starta}} | {{startar}} | {{startade}} | {{startat}}' },
    { id: 'c1_verb_skicka_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'skicka', prompt: { zh: '发送' }, template: '{{skicka}} | {{skickar}} | {{skickade}} | {{skickat}}' },
    { id: 'c1_verb_prata_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'prata', prompt: { zh: '说话 / 谈话' }, template: '{{prata}} | {{pratar}} | {{pratade}} | {{pratat}}' },
    { id: 'c1_verb_verka_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'verka', prompt: { zh: '看起来 / 似乎' }, template: '{{verka}} | {{verkar}} | {{verkade}} | {{verkat}}' },
    { id: 'c1_verb_traffa_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'träffa', prompt: { zh: '遇见' }, template: '{{träffa}} | {{träffar}} | {{träffade}} | {{träffat}}' },
    { id: 'c1_verb_besoka_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'besöka', prompt: { zh: '拜访 / 参观' }, template: '{{besöka}} | {{besöker}} | {{besökte}} | {{besökt}}' },
    { id: 'c1_verb_aka_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'åka', prompt: { zh: '旅行 / 去' }, template: '{{åka}} | {{åker}} | {{åkte}} | {{åkt}}' },
    { id: 'c1_verb_bo_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'bo', prompt: { zh: '居住' }, template: '{{bo}} | {{bor}} | {{bodde}} | {{bott}}' },
    { id: 'c1_verb_handa_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'hända', prompt: { zh: '发生' }, template: '{{hända}} | {{händer}} | {{hände}} | {{hänt}}' },
    // ===== noun_forms =====
    { id: 'c1_noun_helg_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'helg', prompt: { zh: '周末' }, template: '{{en}} | {{helg}} | {{helgen}} | {{helger}} | {{helgerna}}' },
    { id: 'c1_noun_familj_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'familj', prompt: { zh: '家庭' }, template: '{{en}} | {{familj}} | {{familjen}} | {{familjer}} | {{familjerna}}' },
    { id: 'c1_noun_hotell_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'hotell', prompt: { zh: '酒店' }, template: '{{ett}} | {{hotell}} | {{hotellet}} | {{hotell}} | {{hotellen}}' },
    { id: 'c1_noun_hamn_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'hamn', prompt: { zh: '港口' }, template: '{{en}} | {{hamn}} | {{hamnen}} | {{hamnar}} | {{hamnarna}}' },
    { id: 'c1_noun_mote_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'möte', prompt: { zh: '会议' }, template: '{{ett}} | {{möte}} | {{mötet}} | {{möten}} | {{mötena}}' },
    { id: 'c1_noun_projekt_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'projekt', prompt: { zh: '项目' }, template: '{{ett}} | {{projekt}} | {{projektet}} | {{projekt}} | {{projekten}}' },
    { id: 'c1_noun_plan_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'plan', prompt: { zh: '计划' }, template: '{{en}} | {{plan}} | {{planen}} | {{planer}} | {{planerna}}' },
    { id: 'c1_noun_mejl_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'mejl', prompt: { zh: '邮件' }, template: '{{ett}} | {{mejl}} | {{mejlet}} | {{mejl}} | {{mejlen}}' },
    { id: 'c1_noun_mage_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'mage', prompt: { zh: '肚子 / 胃' }, template: '{{en}} | {{mage}} | {{magen}} | {{magar}} | {{magarna}}' }
  ]
};
