window.UNIT_BANK_C2 = {
  unit: 'c2',
  unitTitle: '情态动词',
  basicPool: [
    // ===== 单词题 =====
    { id: 'c2_vocab_kunna', kind: 'vocab_spelling', concept: 'kunna', lemma: 'kunna', source: 'vocab', prompt: { zh: '能 / 会（动词原形）' }, answer: 'kunna' },
    { id: 'c2_vocab_vilja', kind: 'vocab_spelling', concept: 'vilja', lemma: 'vilja', source: 'vocab', prompt: { zh: '想要（动词原形）' }, answer: 'vilja' },
    { id: 'c2_vocab_skola', kind: 'vocab_spelling', concept: 'skola', lemma: 'skola', source: 'vocab', prompt: { zh: '将要 / 打算（动词原形）' }, answer: 'skola' },
    { id: 'c2_vocab_maste', kind: 'vocab_spelling', concept: 'måste', lemma: 'måste', source: 'vocab', prompt: { zh: '必须（动词原形）' }, answer: 'måste' },
    { id: 'c2_vocab_fa', kind: 'vocab_spelling', concept: 'få', lemma: 'få', source: 'vocab', prompt: { zh: '可以 / 被允许（动词原形）' }, answer: 'få' },
    { id: 'c2_vocab_bora', kind: 'vocab_spelling', concept: 'böra', lemma: 'böra', source: 'vocab', prompt: { zh: '应该（动词原形）' }, answer: 'böra' },
    { id: 'c2_vocab_behova', kind: 'vocab_spelling', concept: 'behöva', lemma: 'behöva', source: 'vocab', prompt: { zh: '需要（动词原形）' }, answer: 'behöva' },
    { id: 'c2_vocab_simma', kind: 'vocab_spelling', concept: 'simma', lemma: 'simma', source: 'vocab', prompt: { zh: '游泳（动词原形）' }, answer: 'simma' },
    { id: 'c2_vocab_studera', kind: 'vocab_spelling', concept: 'studera', lemma: 'studera', source: 'vocab', prompt: { zh: '学习（动词原形）' }, answer: 'studera' },
    { id: 'c2_vocab_resa', kind: 'vocab_spelling', concept: 'resa', lemma: 'resa', source: 'vocab', prompt: { zh: '旅行（动词原形）' }, answer: 'resa' },
    { id: 'c2_vocab_komma', kind: 'vocab_spelling', concept: 'komma', lemma: 'komma', source: 'vocab', prompt: { zh: '来（动词原形）' }, answer: 'komma' },
    { id: 'c2_vocab_jobba', kind: 'vocab_spelling', concept: 'jobba', lemma: 'jobba', source: 'vocab', prompt: { zh: '工作（动词原形）' }, answer: 'jobba' },
    { id: 'c2_vocab_traffa', kind: 'vocab_spelling', concept: 'träffa', lemma: 'träffa', source: 'vocab', prompt: { zh: '见面 / 见到（动词原形）' }, answer: 'träffa' },
    { id: 'c2_vocab_boka', kind: 'vocab_spelling', concept: 'boka', lemma: 'boka', source: 'vocab', prompt: { zh: '预约 / 预订（动词原形）' }, answer: 'boka' },
    { id: 'c2_vocab_ta_ledigt', kind: 'vocab_spelling', concept: 'ta ledigt', lemma: 'ta ledigt', source: 'vocab', prompt: { zh: '请假（动词原形）' }, answer: 'ta ledigt' },
    { id: 'c2_vocab_gora', kind: 'vocab_spelling', concept: 'göra', lemma: 'göra', source: 'vocab', prompt: { zh: '做（动词原形）' }, answer: 'göra' },
    { id: 'c2_vocab_ga', kind: 'vocab_spelling', concept: 'gå', lemma: 'gå', source: 'vocab', prompt: { zh: '去（动词原形）' }, answer: 'gå' },
    { id: 'c2_vocab_vara', kind: 'vocab_spelling', concept: 'vara', lemma: 'vara', source: 'vocab', prompt: { zh: '在 / 保持（动词原形）' }, answer: 'vara' },
    { id: 'c2_vocab_borja', kind: 'vocab_spelling', concept: 'börja', lemma: 'börja', source: 'vocab', prompt: { zh: '开始（动词原形）' }, answer: 'börja' },
    { id: 'c2_vocab_meddela', kind: 'vocab_spelling', concept: 'meddela', lemma: 'meddela', source: 'vocab', prompt: { zh: '通知（动词原形）' }, answer: 'meddela' },
    { id: 'c2_vocab_hjalpa', kind: 'vocab_spelling', concept: 'hjälpa', lemma: 'hjälpa', source: 'vocab', prompt: { zh: '帮助（动词原形）' }, answer: 'hjälpa' },
    { id: 'c2_vocab_oppna', kind: 'vocab_spelling', concept: 'öppna', lemma: 'öppna', source: 'vocab', prompt: { zh: '开窗（动词原形）' }, answer: 'öppna' },
    { id: 'c2_vocab_visa', kind: 'vocab_spelling', concept: 'visa', lemma: 'visa', source: 'vocab', prompt: { zh: '出示（动词原形）' }, answer: 'visa' },
    { id: 'c2_vocab_mojlighet', kind: 'vocab_spelling', concept: 'möjlighet', lemma: 'möjlighet', source: 'vocab', prompt: { zh: '可能性 / 机会（名词，单数）' }, answer: 'en möjlighet' },
    { id: 'c2_vocab_tillstand', kind: 'vocab_spelling', concept: 'tillstånd', lemma: 'tillstånd', source: 'vocab', prompt: { zh: '许可 / 状态（名词，单数）' }, answer: 'ett tillstånd' },
    { id: 'c2_vocab_skyldighet', kind: 'vocab_spelling', concept: 'skyldighet', lemma: 'skyldighet', source: 'vocab', prompt: { zh: '义务 / 责任（名词，单数）' }, answer: 'en skyldighet' },
    { id: 'c2_vocab_formaga', kind: 'vocab_spelling', concept: 'förmåga', lemma: 'förmåga', source: 'vocab', prompt: { zh: '能力（名词，单数）' }, answer: 'en förmåga' },
    { id: 'c2_vocab_val', kind: 'vocab_spelling', concept: 'val', lemma: 'val', source: 'vocab', prompt: { zh: '选择（名词，单数）' }, answer: 'ett val' },
    { id: 'c2_vocab_kanske', kind: 'vocab_spelling', concept: 'kanske', lemma: 'kanske', source: 'vocab', prompt: { zh: '也许 / 可能' }, answer: 'kanske' },
    { id: 'c2_vocab_garna', kind: 'vocab_spelling', concept: 'gärna', lemma: 'gärna', source: 'vocab', prompt: { zh: '乐意地 / 当然可以' }, answer: 'gärna' },
    { id: 'c2_vocab_tyvarr', kind: 'vocab_spelling', concept: 'tyvärr', lemma: 'tyvärr', source: 'vocab', prompt: { zh: '可惜 / 遗憾' }, answer: 'tyvärr' },
    { id: 'c2_vocab_absolut', kind: 'vocab_spelling', concept: 'absolut', lemma: 'absolut', source: 'vocab', prompt: { zh: '绝对 / 当然' }, answer: 'absolut' },
    { id: 'c2_vocab_troligen', kind: 'vocab_spelling', concept: 'troligen', lemma: 'troligen', source: 'vocab', prompt: { zh: '很可能 / 大概' }, answer: 'troligen' },
    { id: 'c2_vocab_definitivt', kind: 'vocab_spelling', concept: 'definitivt', lemma: 'definitivt', source: 'vocab', prompt: { zh: '肯定 / 确定地' }, answer: 'definitivt' },
    // ===== 固定表达题 =====
    { id: 'c2_phrase_jag_kan_kora_bil', kind: 'phrase_fill', concept: 'jag_kan_kora_bil', lemma: 'kan', source: 'phrase', prompt: { zh: '我会开车。' }, template: 'Jag {{kan}} köra bil.' },
    { id: 'c2_phrase_du_maste_studera', kind: 'phrase_fill', concept: 'du_maste_studera', lemma: 'måste', source: 'phrase', prompt: { zh: '你必须学习。' }, template: 'Du {{måste}} studera.' },
    { id: 'c2_phrase_vi_ska_resa_till_sverige', kind: 'phrase_fill', concept: 'vi_ska_resa_till_sverige', lemma: 'ska', source: 'phrase', prompt: { zh: '我们将去瑞典旅行。' }, template: 'Vi {{ska}} resa till Sverige.' },
    { id: 'c2_phrase_jag_vill_ata_pizza', kind: 'phrase_fill', concept: 'jag_vill_ata_pizza', lemma: 'vill', source: 'phrase', prompt: { zh: '我想吃披萨。' }, template: 'Jag {{vill}} äta pizza.' },
    { id: 'c2_phrase_far_jag_oppna_fonstret', kind: 'phrase_fill', concept: 'far_jag_oppna_fonstret', lemma: 'får', source: 'phrase', prompt: { zh: '我可以开窗吗？' }, template: '{{Får}} jag öppna fönstret?' },
    { id: 'c2_phrase_du_bor_sova_mer', kind: 'phrase_fill', concept: 'du_bor_sova_mer', lemma: 'bör', source: 'phrase', prompt: { zh: '你应该多睡觉。' }, template: 'Du {{bör}} sova mer.' },
    { id: 'c2_phrase_jag_behover_inte_arbeta_pa_lordag', kind: 'phrase_fill', concept: 'jag_behover_inte_arbeta_pa_lordag', lemma: 'behöver', source: 'phrase', prompt: { zh: '我周六不需要工作。' }, template: 'Jag {{behöver}} inte arbeta på lördag.' },
    { id: 'c2_phrase_kan_du_hjalpa_mig', kind: 'phrase_fill', concept: 'kan_du_hjalpa_mig', lemma: 'kan', source: 'phrase', prompt: { zh: '你能帮我吗？' }, template: '{{Kan}} du hjälpa mig?' },
    { id: 'c2_phrase_jag_kunde_inte_sova', kind: 'phrase_fill', concept: 'jag_kunde_inte_sova', lemma: 'kunde', source: 'phrase', prompt: { zh: '我那时睡不着。' }, template: 'Jag {{kunde}} inte sova.' },
    { id: 'c2_phrase_du_maste_visa_legitimation', kind: 'phrase_fill', concept: 'du_maste_visa_legitimation', lemma: 'måste', source: 'phrase', prompt: { zh: '你必须出示证件。' }, template: 'Du {{måste}} visa legitimation.' },
    { id: 'c2_phrase_vi_ska_flytta_till_malmo', kind: 'phrase_fill', concept: 'vi_ska_flytta_till_malmo', lemma: 'ska', source: 'phrase', prompt: { zh: '我们明年打算搬去马尔默。' }, template: 'Vi {{ska}} flytta till Malmö nästa år.' },
    { id: 'c2_phrase_ska_du_arbeta_imorgon', kind: 'phrase_fill', concept: 'ska_du_arbeta_imorgon', lemma: 'ska', source: 'phrase', prompt: { zh: '你明天要工作吗？' }, template: '{{Ska}} du arbeta imorgon?' },
    { id: 'c2_phrase_far_man_parkera_har', kind: 'phrase_fill', concept: 'far_man_parkera_har', lemma: 'får', source: 'phrase', prompt: { zh: '这里可以停车吗？' }, template: '{{Får}} man parkera här?' },
    { id: 'c2_phrase_du_maste_inte_komma', kind: 'phrase_fill', concept: 'du_maste_inte_komma', lemma: 'måste', source: 'phrase', prompt: { zh: '你不必来。' }, template: 'Du {{måste}} inte komma.' },
    { id: 'c2_phrase_du_far_inte_roka_har', kind: 'phrase_fill', concept: 'du_far_inte_roka_har', lemma: 'får', source: 'phrase', prompt: { zh: '你不能在这里抽烟。' }, template: 'Du {{får}} inte röka här.' },
    { id: 'c2_phrase_jag_kan_simma', kind: 'phrase_fill', concept: 'jag_kan_simma', lemma: 'kan', source: 'phrase', prompt: { zh: '我会游泳。' }, template: 'Jag {{kan}} simma.' },
    { id: 'c2_phrase_jag_kan_inte_simma', kind: 'phrase_fill', concept: 'jag_kan_inte_simma', lemma: 'inte', source: 'phrase', prompt: { zh: '我不能游泳。' }, template: 'Jag kan {{inte}} simma.' },
    { id: 'c2_phrase_hon_vill_inte_ata', kind: 'phrase_fill', concept: 'hon_vill_inte_ata', lemma: 'inte', source: 'phrase', prompt: { zh: '我不想吃。' }, template: 'Hon vill {{inte}} äta.' },
    { id: 'c2_phrase_kan_du_svenska', kind: 'phrase_fill', concept: 'kan_du_svenska', lemma: 'kan', source: 'phrase', prompt: { zh: '你会瑞典语吗？' }, template: '{{Kan}} du svenska?' },
    { id: 'c2_phrase_maste_vi_ga_nu', kind: 'phrase_fill', concept: 'maste_vi_ga_nu', lemma: 'måste', source: 'phrase', prompt: { zh: '我们现在必须走吗？' }, template: '{{Måste}} vi gå nu?' },
    // ===== 对话句题 =====
    { id: 'c2_dialog_kan_du_komma_pa_festen', kind: 'dialog_fill', concept: 'kan_du_komma_pa_festen', lemma: 'kan', source: 'dialog', prompt: { zh: '你周五能来派对吗？' }, template: '{{Kan}} du komma på festen på fredag?' },
    { id: 'c2_dialog_tyvarr_kan_jag_inte', kind: 'dialog_fill', concept: 'tyvarr_kan_jag_inte', lemma: 'inte', source: 'dialog', prompt: { zh: '很遗憾，我不能来。' }, template: 'Tyvärr kan jag {{inte}}.' },
    { id: 'c2_dialog_jag_maste_jobba_sent', kind: 'dialog_fill', concept: 'jag_maste_jobba_sent', lemma: 'måste', source: 'dialog', prompt: { zh: '那天晚上我必须工作到很晚。' }, template: 'Jag {{måste}} jobba sent den kvällen.' },
    { id: 'c2_dialog_ska_du_jobba_hela_helgen', kind: 'dialog_fill', concept: 'ska_du_jobba_hela_helgen', lemma: 'ska', source: 'dialog', prompt: { zh: '你整个周末都要工作吗？' }, template: '{{Ska}} du jobba hela helgen?' },
    { id: 'c2_dialog_men_jag_vill_garna_traffa_er_snart', kind: 'dialog_fill', concept: 'men_jag_vill_garna_traffa_er_snart', lemma: 'vill', source: 'dialog', prompt: { zh: '但我很想尽快见到你们！' }, template: 'Men jag {{vill}} gärna träffa er snart!' },
    { id: 'c2_dialog_vi_kan_traffas_pa_lordag_istallet', kind: 'dialog_fill', concept: 'vi_kan_traffas_pa_lordag_istallet', lemma: 'kan', source: 'dialog', prompt: { zh: '我们可以改到周六见。' }, template: 'Vi {{kan}} träffas på lördag istället.' },
    { id: 'c2_dialog_du_behover_inte_boka', kind: 'dialog_fill', concept: 'du_behover_inte_boka', lemma: 'behöver', source: 'dialog', prompt: { zh: '你不需要预约。' }, template: 'Du {{behöver}} inte boka.' },
    { id: 'c2_dialog_jag_ska_definitivt_komma_da', kind: 'dialog_fill', concept: 'jag_ska_definitivt_komma_da', lemma: 'ska', source: 'dialog', prompt: { zh: '我那时候肯定来。' }, template: 'Jag {{ska}} definitivt komma då.' },
    { id: 'c2_dialog_far_jag_ta_ledigt_nasta_tisdag', kind: 'dialog_fill', concept: 'far_jag_ta_ledigt_nasta_tisdag', lemma: 'får', source: 'dialog', prompt: { zh: '我下周二可以请假吗？' }, template: '{{Får}} jag ta ledigt nästa tisdag?' },
    { id: 'c2_dialog_vad_ska_du_gora', kind: 'dialog_fill', concept: 'vad_ska_du_gora', lemma: 'ska', source: 'dialog', prompt: { zh: '你要去做什么？' }, template: 'Vad {{ska}} du göra?' },
    { id: 'c2_dialog_jag_behover_ga_till_lakaren', kind: 'dialog_fill', concept: 'jag_behover_ga_till_lakaren', lemma: 'behöver', source: 'dialog', prompt: { zh: '我需要去看医生。' }, template: 'Jag {{behöver}} gå till läkaren.' },
    { id: 'c2_dialog_det_borde_du_absolut_kunna_gora', kind: 'dialog_fill', concept: 'det_borde_du_absolut_kunna_gora', lemma: 'borde', source: 'dialog', prompt: { zh: '这当然应该能做。' }, template: 'Det {{borde}} du absolut kunna göra.' },
    { id: 'c2_dialog_hur_lange_behover_du_vara_borta', kind: 'dialog_fill', concept: 'hur_lange_behover_du_vara_borta', lemma: 'behöver', source: 'dialog', prompt: { zh: '你需要离开多久？' }, template: 'Hur länge {{behöver}} du vara borta?' },
    { id: 'c2_dialog_kan_jag_borja_lite_senare', kind: 'dialog_fill', concept: 'kan_jag_borja_lite_senare', lemma: 'kan', source: 'dialog', prompt: { zh: '我可以早上晚点开始吗？' }, template: '{{Kan}} jag börja lite senare på morgonen?' },
    { id: 'c2_dialog_du_maste_bara_meddela_mig', kind: 'dialog_fill', concept: 'du_maste_bara_meddela_mig', lemma: 'måste', source: 'dialog', prompt: { zh: '你只需要提前通知我。' }, template: 'Du {{måste}} bara meddela mig i förväg.' }
  ],
  advancedPool: [
    // ===== verb_forms =====
    { id: 'c2_verb_kunna_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'kunna', prompt: { zh: '能 / 会' }, template: '{{kunna}} | {{kan}} | {{kunde}} | {{kunnat}}' },
    { id: 'c2_verb_vilja_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'vilja', prompt: { zh: '想要' }, template: '{{vilja}} | {{vill}} | {{ville}} | {{velat}}' },
    { id: 'c2_verb_skola_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'skola', prompt: { zh: '将要 / 打算' }, template: '{{skola}} | {{ska}} | {{skulle}} | {{skolat}}' },
    { id: 'c2_verb_maste_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'måste', prompt: { zh: '必须' }, template: '{{måste}} | {{måste}} | {{måste}} | {{måst}}' },
    { id: 'c2_verb_fa_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'få', prompt: { zh: '可以 / 被允许' }, template: '{{få}} | {{får}} | {{fick}} | {{fått}}' },
    { id: 'c2_verb_bora_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'böra', prompt: { zh: '应该' }, template: '{{böra}} | {{bör}} | {{borde}} | {{bort}}' },
    { id: 'c2_verb_behova_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'behöva', prompt: { zh: '需要' }, template: '{{behöva}} | {{behöver}} | {{behövde}} | {{behövt}}' },
    // ===== noun_forms =====
    { id: 'c2_noun_mojlighet_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'möjlighet', prompt: { zh: '可能性 / 机会' }, template: '{{en}} | {{möjlighet}} | {{möjligheten}} | {{möjligheter}} | {{möjligheterna}}' },
    { id: 'c2_noun_tillstand_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'tillstånd', prompt: { zh: '许可 / 状态' }, template: '{{ett}} | {{tillstånd}} | {{tillståndet}} | {{tillstånd}} | {{tillstånden}}' },
    { id: 'c2_noun_skyldighet_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'skyldighet', prompt: { zh: '义务 / 责任' }, template: '{{en}} | {{skyldighet}} | {{skyldigheten}} | {{skyldigheter}} | {{skyldigheterna}}' },
    { id: 'c2_noun_formaga_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'förmåga', prompt: { zh: '能力' }, template: '{{en}} | {{förmåga}} | {{förmågan}} | {{förmågor}} | {{förmågorna}}' },
    { id: 'c2_noun_val_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'val', prompt: { zh: '选择' }, template: '{{ett}} | {{val}} | {{valet}} | {{val}} | {{valen}}' },
    // ===== negation / question pattern =====
    { id: 'c2_neg_jag_kan_inte_simma', kind: 'morphology', source: 'pattern', lemma: 'jag kan inte simma', prompt: { zh: '否定句' }, template: 'Jag kan {{inte}} simma.' },
    { id: 'c2_neg_hon_vill_inte_ata', kind: 'morphology', source: 'pattern', lemma: 'hon vill inte äta', prompt: { zh: '否定句' }, template: 'Hon vill {{inte}} äta.' },
    { id: 'c2_neg_jag_behover_inte_arbeta', kind: 'morphology', source: 'pattern', lemma: 'jag behöver inte arbeta på lördag', prompt: { zh: '否定句' }, template: 'Jag behöver {{inte}} arbeta på lördag.' },
    { id: 'c2_neg_du_far_inte_roka_har', kind: 'morphology', source: 'pattern', lemma: 'du får inte röka här', prompt: { zh: '否定句' }, template: 'Du får {{inte}} röka här.' },
    { id: 'c2_q_kan_du_svenska', kind: 'morphology', source: 'pattern', lemma: 'kan du svenska', prompt: { zh: '疑问句' }, template: '{{Kan}} du svenska?' },
    { id: 'c2_q_maste_vi_ga_nu', kind: 'morphology', source: 'pattern', lemma: 'måste vi gå nu', prompt: { zh: '疑问句' }, template: '{{Måste}} vi gå nu?' },
    { id: 'c2_q_far_jag_oppna_fonstret', kind: 'morphology', source: 'pattern', lemma: 'får jag öppna fönstret', prompt: { zh: '疑问句' }, template: '{{Får}} jag öppna fönstret?' },
    { id: 'c2_q_ska_du_arbeta_imorgon', kind: 'morphology', source: 'pattern', lemma: 'ska du arbeta imorgon', prompt: { zh: '疑问句' }, template: '{{Ska}} du arbeta imorgon?' }
  ]
};
