window.UNIT_BANK_C3 = {
  unit: 'c3',
  unitTitle: '从句入门',
  basicPool: [
    // ===== 单词题 =====
    { id: 'c3_vocab_tro', kind: 'vocab_spelling', concept: 'tro', lemma: 'tro', source: 'vocab', prompt: { zh: '认为 / 相信（动词原形）' }, answer: 'tro' },
    { id: 'c3_vocab_veta', kind: 'vocab_spelling', concept: 'veta', lemma: 'veta', source: 'vocab', prompt: { zh: '知道（动词原形）' }, answer: 'veta' },
    { id: 'c3_vocab_tycka', kind: 'vocab_spelling', concept: 'tycka', lemma: 'tycka', source: 'vocab', prompt: { zh: '觉得 / 认为（动词原形）' }, answer: 'tycka' },
    { id: 'c3_vocab_hoppas', kind: 'vocab_spelling', concept: 'hoppas', lemma: 'hoppas', source: 'vocab', prompt: { zh: '希望（动词原形）' }, answer: 'hoppas' },
    { id: 'c3_vocab_beratta', kind: 'vocab_spelling', concept: 'berätta', lemma: 'berätta', source: 'vocab', prompt: { zh: '讲述 / 告诉（动词原形）' }, answer: 'berätta' },
    { id: 'c3_vocab_fraga', kind: 'vocab_spelling', concept: 'fråga', lemma: 'fråga', source: 'vocab', prompt: { zh: '询问（动词原形）' }, answer: 'fråga' },
    { id: 'c3_vocab_forsta', kind: 'vocab_spelling', concept: 'förstå', lemma: 'förstå', source: 'vocab', prompt: { zh: '理解 / 明白（动词原形）' }, answer: 'förstå' },
    { id: 'c3_vocab_undra', kind: 'vocab_spelling', concept: 'undra', lemma: 'undra', source: 'vocab', prompt: { zh: '想知道 / 纳闷（动词原形）' }, answer: 'undra' },
    { id: 'c3_vocab_mening', kind: 'vocab_spelling', concept: 'mening', lemma: 'mening', source: 'vocab', prompt: { zh: '句子 / 意思（名词，单数）' }, answer: 'en mening' },
    { id: 'c3_vocab_svar', kind: 'vocab_spelling', concept: 'svar', lemma: 'svar', source: 'vocab', prompt: { zh: '回答 / 答案（名词，单数）' }, answer: 'ett svar' },
    { id: 'c3_vocab_fraga_noun', kind: 'vocab_spelling', concept: 'fråga_noun', lemma: 'fråga', source: 'vocab', prompt: { zh: '问题（名词，单数）' }, answer: 'en fråga' },
    { id: 'c3_vocab_tanke', kind: 'vocab_spelling', concept: 'tanke', lemma: 'tanke', source: 'vocab', prompt: { zh: '想法 / 念头（名词，单数）' }, answer: 'en tanke' },
    { id: 'c3_vocab_skal', kind: 'vocab_spelling', concept: 'skäl', lemma: 'skäl', source: 'vocab', prompt: { zh: '理由 / 原因（名词，单数）' }, answer: 'ett skäl' },
    { id: 'c3_vocab_att', kind: 'vocab_spelling', concept: 'att', lemma: 'att', source: 'vocab', prompt: { zh: 'that（引导宾语从句）' }, answer: 'att' },
    { id: 'c3_vocab_som', kind: 'vocab_spelling', concept: 'som', lemma: 'som', source: 'vocab', prompt: { zh: 'who / which / that（引导关系从句）' }, answer: 'som' },
    { id: 'c3_vocab_om', kind: 'vocab_spelling', concept: 'om', lemma: 'om', source: 'vocab', prompt: { zh: 'if / whether（引导间接疑问）' }, answer: 'om' },
    { id: 'c3_vocab_eftersom', kind: 'vocab_spelling', concept: 'eftersom', lemma: 'eftersom', source: 'vocab', prompt: { zh: 'because / since（因为）' }, answer: 'eftersom' },
    { id: 'c3_vocab_for_att', kind: 'vocab_spelling', concept: 'för att', lemma: 'för att', source: 'vocab', prompt: { zh: 'in order to（为了）' }, answer: 'för att' },
    { id: 'c3_vocab_fastan', kind: 'vocab_spelling', concept: 'fastän', lemma: 'fastän', source: 'vocab', prompt: { zh: 'although（尽管）' }, answer: 'fastän' },
    { id: 'c3_vocab_medan', kind: 'vocab_spelling', concept: 'medan', lemma: 'medan', source: 'vocab', prompt: { zh: 'while（当……同时）' }, answer: 'medan' },
    { id: 'c3_vocab_tills', kind: 'vocab_spelling', concept: 'tills', lemma: 'tills', source: 'vocab', prompt: { zh: 'until（直到）' }, answer: 'tills' },
    // ===== 固定表达题 =====
    { id: 'c3_phrase_jag_tror_att_det_regnar', kind: 'phrase_fill', concept: 'jag_tror_att_det_regnar', lemma: 'att', source: 'phrase', prompt: { zh: '我认为明天会下雨。' }, template: 'Jag tror {{att}} det regnar imorgon.' },
    { id: 'c3_phrase_hon_sager_att_hon_ar_trott', kind: 'phrase_fill', concept: 'hon_sager_att_hon_ar_trott', lemma: 'att', source: 'phrase', prompt: { zh: '她说她很累。' }, template: 'Hon säger {{att}} hon är trött.' },
    { id: 'c3_phrase_vi_hoppas_att_allt_gar_bra', kind: 'phrase_fill', concept: 'vi_hoppas_att_allt_gar_bra', lemma: 'att', source: 'phrase', prompt: { zh: '我们希望一切顺利。' }, template: 'Vi hoppas {{att}} allt går bra.' },
    { id: 'c3_phrase_jag_vet_att_han_inte_arbetar', kind: 'phrase_fill', concept: 'jag_vet_att_han_inte_arbetar', lemma: 'inte', source: 'phrase', prompt: { zh: '我知道他不工作。' }, template: 'Jag vet att han {{inte}} arbetar.' },
    { id: 'c3_phrase_jag_tror_att_han_inte_kommer', kind: 'phrase_fill', concept: 'jag_tror_att_han_inte_kommer', lemma: 'inte', source: 'phrase', prompt: { zh: '我觉得他不会来。' }, template: 'Jag tror att han {{inte}} kommer.' },
    { id: 'c3_phrase_vi_vet_att_de_inte_vet', kind: 'phrase_fill', concept: 'vi_vet_att_de_inte_vet', lemma: 'inte', source: 'phrase', prompt: { zh: '我们知道他们不知道。' }, template: 'Vi vet att de {{inte}} vet.' },
    { id: 'c3_phrase_jag_har_en_kompis_som_bor_i_goteborg', kind: 'phrase_fill', concept: 'jag_har_en_kompis_som_bor_i_goteborg', lemma: 'som', source: 'phrase', prompt: { zh: '我有一个住在哥德堡的朋友。' }, template: 'Jag har en kompis {{som}} bor i Göteborg.' },
    { id: 'c3_phrase_det_ar_boken_som_jag_laste_igar', kind: 'phrase_fill', concept: 'det_ar_boken_som_jag_laste_igar', lemma: 'som', source: 'phrase', prompt: { zh: '那是我昨天读的书。' }, template: 'Det är boken {{som}} jag läste igår.' },
    { id: 'c3_phrase_lararen_som_undervisar_oss_ar_bra', kind: 'phrase_fill', concept: 'lararen_som_undervisar_oss_ar_bra', lemma: 'som', source: 'phrase', prompt: { zh: '教我们的老师很好。' }, template: 'Läraren {{som}} undervisar oss är bra.' },
    { id: 'c3_phrase_vet_du_om_hon_kommer_imorgon', kind: 'phrase_fill', concept: 'vet_du_om_hon_kommer_imorgon', lemma: 'om', source: 'phrase', prompt: { zh: '你知道她明天是否来吗？' }, template: 'Vet du {{om}} hon kommer imorgon?' },
    { id: 'c3_phrase_jag_vet_inte_om_det_ar_oppet', kind: 'phrase_fill', concept: 'jag_vet_inte_om_det_ar_oppet', lemma: 'om', source: 'phrase', prompt: { zh: '我不知道图书馆是否开门。' }, template: 'Jag vet inte {{om}} det är öppet.' },
    { id: 'c3_phrase_kan_du_visa_mig_hur_jag_hittar_dit', kind: 'phrase_fill', concept: 'kan_du_visa_mig_hur_jag_hittar_dit', lemma: 'hur', source: 'phrase', prompt: { zh: '你能告诉我怎么去那里吗？' }, template: 'Kan du visa mig {{hur}} jag hittar dit?' },
    { id: 'c3_phrase_jag_stannar_hemma_eftersom_jag_ar_sjuk', kind: 'phrase_fill', concept: 'jag_stannar_hemma_eftersom_jag_ar_sjuk', lemma: 'eftersom', source: 'phrase', prompt: { zh: '我待在家里，因为我生病了。' }, template: 'Jag stannar hemma {{eftersom}} jag är sjuk.' },
    { id: 'c3_phrase_han_studerar_for_att_lara_sig_svenska', kind: 'phrase_fill', concept: 'han_studerar_for_att_lara_sig_svenska', lemma: 'för att', source: 'phrase', prompt: { zh: '他学习是为了学瑞典语。' }, template: 'Han studerar {{för att}} lära sig svenska.' },
    { id: 'c3_phrase_hon_kom_fastan_hon_var_trott', kind: 'phrase_fill', concept: 'hon_kom_fastan_hon_var_trott', lemma: 'fastän', source: 'phrase', prompt: { zh: '她来了，尽管她很累。' }, template: 'Hon kom {{fastän}} hon var trött.' },
    { id: 'c3_phrase_vanta_tills_jag_kommer_tillbaka', kind: 'phrase_fill', concept: 'vanta_tills_jag_kommer_tillbaka', lemma: 'tills', source: 'phrase', prompt: { zh: '等到我回来。' }, template: 'Vänta {{tills}} jag kommer tillbaka.' },
    // ===== 对话句题 =====
    { id: 'c3_dialog_jag_har_hort_att_du_ska_flytta_snart', kind: 'dialog_fill', concept: 'jag_har_hort_att_du_ska_flytta_snart', lemma: 'att', source: 'dialog', prompt: { zh: '我听说你快要搬家了。是真的吗？' }, template: 'Jag har hört {{att}} du ska flytta snart. Stämmer det?' },
    { id: 'c3_dialog_ja_jag_tror_att_det_blir_nasta_manad', kind: 'dialog_fill', concept: 'ja_jag_tror_att_det_blir_nasta_manad', lemma: 'att', source: 'dialog', prompt: { zh: '是的，我觉得会是下个月。' }, template: 'Ja, jag tror {{att}} det blir nästa månad.' },
    { id: 'c3_dialog_vi_har_hittat_en_lagenhet_som_ligger_nara_centrum', kind: 'dialog_fill', concept: 'vi_har_hittat_en_lagenhet_som_ligger_nara_centrum', lemma: 'som', source: 'dialog', prompt: { zh: '我们找到了一套位于市中心附近的公寓。' }, template: 'Vi har hittat en lägenhet {{som}} ligger nära centrum.' },
    { id: 'c3_dialog_jag_hoppas_att_allt_gar_bra', kind: 'dialog_fill', concept: 'jag_hoppas_att_allt_gar_bra_dialog', lemma: 'att', source: 'dialog', prompt: { zh: '我希望一切顺利。' }, template: 'Jag hoppas {{att}} allt går bra.' },
    { id: 'c3_dialog_jag_vet_att_det_ordnar_sig', kind: 'dialog_fill', concept: 'jag_vet_att_det_ordnar_sig', lemma: 'att', source: 'dialog', prompt: { zh: '我知道会好起来的。' }, template: 'Jag vet {{att}} det ordnar sig.' },
    { id: 'c3_dialog_och_grannen_som_du_berattade_om', kind: 'dialog_fill', concept: 'och_grannen_som_du_berattade_om', lemma: 'som', source: 'dialog', prompt: { zh: '那个你说过的邻居怎么样？' }, template: 'Och grannen {{som}} du berättade om, hur är han?' },
    { id: 'c3_dialog_jag_forstar_att_vi_kommer_att_trivas', kind: 'dialog_fill', concept: 'jag_forstar_att_vi_kommer_att_trivas', lemma: 'att', source: 'dialog', prompt: { zh: '我觉得我们会相处愉快。' }, template: 'Jag förstår {{att}} vi kommer att trivas bra ihop.' },
    { id: 'c3_dialog_jag_undrar_var_biblioteket_ligger', kind: 'dialog_fill', concept: 'jag_undrar_var_biblioteket_ligger', lemma: 'var', source: 'dialog', prompt: { zh: '我想知道图书馆在哪里。' }, template: 'Jag undrar {{var}} biblioteket ligger.' },
    { id: 'c3_dialog_jag_tror_att_det_ar_pa_storgatan', kind: 'dialog_fill', concept: 'jag_tror_att_det_ar_pa_storgatan', lemma: 'att', source: 'dialog', prompt: { zh: '我觉得它在大街上。' }, template: 'Jag tror {{att}} det är på Storgatan.' },
    { id: 'c3_dialog_vet_du_om_det_ar_oppet_nu', kind: 'dialog_fill', concept: 'vet_du_om_det_ar_oppet_nu', lemma: 'om', source: 'dialog', prompt: { zh: '你知道它现在开着吗？' }, template: 'Vet du {{om}} det är öppet nu?' },
    { id: 'c3_dialog_jag_vet_inte_om_det_ar_oppet_pa_sondagar', kind: 'dialog_fill', concept: 'jag_vet_inte_om_det_ar_oppet_pa_sondagar', lemma: 'om', source: 'dialog', prompt: { zh: '我不知道它周日是否开门。' }, template: 'Jag vet inte {{om}} det är öppet på söndagar.' },
    { id: 'c3_dialog_kan_du_visa_mig_hur_jag_hittar_dit_dialog', kind: 'dialog_fill', concept: 'kan_du_visa_mig_hur_jag_hittar_dit_dialog', lemma: 'hur', source: 'dialog', prompt: { zh: '你能告诉我怎么找到那里吗？' }, template: 'Kan du visa mig {{hur}} jag hittar dit?' },
    { id: 'c3_dialog_det_ar_enkelt_eftersom_det_bara_ar_tva_kvarter', kind: 'dialog_fill', concept: 'det_ar_enkelt_eftersom_det_bara_ar_tva_kvarter', lemma: 'eftersom', source: 'dialog', prompt: { zh: '这很简单，因为从这里只有两个街区。' }, template: 'Det är enkelt {{eftersom}} det bara är två kvarter härifrån.' }
  ],
  advancedPool: [
    // ===== verb_forms =====
    { id: 'c3_verb_tro_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'tro', prompt: { zh: '认为 / 相信' }, template: '{{tro}} | {{tror}} | {{trodde}} | {{trott}}' },
    { id: 'c3_verb_veta_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'veta', prompt: { zh: '知道' }, template: '{{veta}} | {{vet}} | {{visste}} | {{vetat}}' },
    { id: 'c3_verb_tycka_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'tycka', prompt: { zh: '觉得 / 认为' }, template: '{{tycka}} | {{tycker}} | {{tyckte}} | {{tyckt}}' },
    { id: 'c3_verb_hoppas_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'hoppas', prompt: { zh: '希望' }, template: '{{hoppas}} | {{hoppas}} | {{hoppades}} | {{hoppats}}' },
    { id: 'c3_verb_beratta_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'berätta', prompt: { zh: '讲述 / 告诉' }, template: '{{berätta}} | {{berättar}} | {{berättade}} | {{berättat}}' },
    { id: 'c3_verb_fraga_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'fråga', prompt: { zh: '询问' }, template: '{{fråga}} | {{frågar}} | {{frågade}} | {{frågat}}' },
    { id: 'c3_verb_forsta_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'förstå', prompt: { zh: '理解 / 明白' }, template: '{{förstå}} | {{förstår}} | {{förstod}} | {{förstått}}' },
    { id: 'c3_verb_undra_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'undra', prompt: { zh: '想知道 / 纳闷' }, template: '{{undra}} | {{undrar}} | {{undrade}} | {{undrat}}' },
    // ===== noun_forms =====
    { id: 'c3_noun_mening_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'mening', prompt: { zh: '句子 / 意思' }, template: '{{en}} | {{mening}} | {{meningen}} | {{meningar}} | {{meningarna}}' },
    { id: 'c3_noun_svar_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'svar', prompt: { zh: '回答 / 答案' }, template: '{{ett}} | {{svar}} | {{svaret}} | {{svar}} | {{svaren}}' },
    { id: 'c3_noun_fraga_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'fråga', prompt: { zh: '问题' }, template: '{{en}} | {{fråga}} | {{frågan}} | {{frågor}} | {{frågorna}}' },
    { id: 'c3_noun_tanke_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'tanke', prompt: { zh: '想法 / 念头' }, template: '{{en}} | {{tanke}} | {{tanken}} | {{tankar}} | {{tankarna}}' },
    { id: 'c3_noun_skal_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'skäl', prompt: { zh: '理由 / 原因' }, template: '{{ett}} | {{skäl}} | {{skälet}} | {{skäl}} | {{skälen}}' },
    // ===== BIFF / 副词位置专项 =====
    { id: 'c3_biff_han_inte_arbetar', kind: 'morphology', source: 'pattern', lemma: 'att han inte arbetar', prompt: { zh: '主句：Han arbetar inte. / 从句：...' }, template: '... att han {{inte}} {{arbetar}}.' },
    { id: 'c3_biff_hon_inte_kommer', kind: 'morphology', source: 'pattern', lemma: 'att hon inte kommer', prompt: { zh: '主句：Hon kommer inte. / 从句：...' }, template: '... att hon {{inte}} {{kommer}}.' },
    { id: 'c3_biff_de_inte_vet', kind: 'morphology', source: 'pattern', lemma: 'att de inte vet', prompt: { zh: '主句：De vet inte. / 从句：...' }, template: '... att de {{inte}} {{vet}}.' }
  ]
};
