window.UNIT_BANK_C4 = {
  unit: 'c4',
  unitTitle: '间接引语与礼貌表达',
  basicPool: [
    // ===== 单词题 =====
    { id: 'c4_vocab_be_om', kind: 'vocab_spelling', concept: 'be om', lemma: 'be om', source: 'vocab', prompt: { zh: '请求（动词原形）' }, answer: 'be om' },
    { id: 'c4_vocab_erbjuda', kind: 'vocab_spelling', concept: 'erbjuda', lemma: 'erbjuda', source: 'vocab', prompt: { zh: '提供 / 邀请（动词原形）' }, answer: 'erbjuda' },
    { id: 'c4_vocab_tacka', kind: 'vocab_spelling', concept: 'tacka', lemma: 'tacka', source: 'vocab', prompt: { zh: '感谢（动词原形）' }, answer: 'tacka' },
    { id: 'c4_vocab_avboka', kind: 'vocab_spelling', concept: 'avboka', lemma: 'avboka', source: 'vocab', prompt: { zh: '取消预约（动词原形）' }, answer: 'avboka' },
    { id: 'c4_vocab_boka', kind: 'vocab_spelling', concept: 'boka', lemma: 'boka', source: 'vocab', prompt: { zh: '预约 / 预订（动词原形）' }, answer: 'boka' },
    { id: 'c4_vocab_klaga', kind: 'vocab_spelling', concept: 'klaga', lemma: 'klaga', source: 'vocab', prompt: { zh: '投诉 / 抱怨（动词原形）' }, answer: 'klaga' },
    { id: 'c4_vocab_paminnna', kind: 'vocab_spelling', concept: 'påminna', lemma: 'påminna', source: 'vocab', prompt: { zh: '提醒（动词原形）' }, answer: 'påminna' },
    { id: 'c4_vocab_meddela', kind: 'vocab_spelling', concept: 'meddela', lemma: 'meddela', source: 'vocab', prompt: { zh: '通知 / 告知（动词原形）' }, answer: 'meddela' },
    { id: 'c4_vocab_arende', kind: 'vocab_spelling', concept: 'ärende', lemma: 'ärende', source: 'vocab', prompt: { zh: '事务 / 来意（名词，单数）' }, answer: 'ett ärende' },
    { id: 'c4_vocab_klagomal', kind: 'vocab_spelling', concept: 'klagomål', lemma: 'klagomål', source: 'vocab', prompt: { zh: '投诉（名词，单数）' }, answer: 'ett klagomål' },
    { id: 'c4_vocab_bokning', kind: 'vocab_spelling', concept: 'bokning', lemma: 'bokning', source: 'vocab', prompt: { zh: '预订（名词，单数）' }, answer: 'en bokning' },
    { id: 'c4_vocab_bekraftelse', kind: 'vocab_spelling', concept: 'bekräftelse', lemma: 'bekräftelse', source: 'vocab', prompt: { zh: '确认 / 回执（名词，单数）' }, answer: 'en bekräftelse' },
    { id: 'c4_vocab_tidbokning', kind: 'vocab_spelling', concept: 'tidbokning', lemma: 'tidbokning', source: 'vocab', prompt: { zh: '预约时间（名词，单数）' }, answer: 'en tidbokning' },
    { id: 'c4_vocab_vantetid', kind: 'vocab_spelling', concept: 'väntetid', lemma: 'väntetid', source: 'vocab', prompt: { zh: '等待时间（名词，单数）' }, answer: 'en väntetid' },
    { id: 'c4_vocab_skulle_vilja_boka', kind: 'vocab_spelling', concept: 'skulle vilja boka', lemma: 'skulle vilja boka', source: 'vocab', prompt: { zh: '我想预约……' }, answer: 'skulle vilja boka' },
    { id: 'c4_vocab_har_du_mojlighet_att', kind: 'vocab_spelling', concept: 'Har du möjlighet att', lemma: 'Har du möjlighet att', source: 'vocab', prompt: { zh: '你有没有可能……' }, answer: 'Har du möjlighet att' },
    { id: 'c4_vocab_jag_undrar_om', kind: 'vocab_spelling', concept: 'Jag undrar om', lemma: 'Jag undrar om', source: 'vocab', prompt: { zh: '我想知道是否……' }, answer: 'Jag undrar om' },
    { id: 'c4_vocab_skulle_vilja_framfora', kind: 'vocab_spelling', concept: 'skulle vilja framföra', lemma: 'skulle vilja framföra', source: 'vocab', prompt: { zh: '我想提出一个投诉' }, answer: 'skulle vilja framföra' },
    { id: 'c4_vocab_det_skulle_vara_bra_om', kind: 'vocab_spelling', concept: 'Det skulle vara bra om', lemma: 'Det skulle vara bra om', source: 'vocab', prompt: { zh: '如果……就好了' }, answer: 'Det skulle vara bra om' },
    { id: 'c4_vocab_skulle_du_kunna', kind: 'vocab_spelling', concept: 'Skulle du kunna', lemma: 'Skulle du kunna', source: 'vocab', prompt: { zh: '你能否……' }, answer: 'Skulle du kunna' },
    // ===== 固定表达题 =====
    { id: 'c4_phrase_han_sa_att_han_var_trott', kind: 'phrase_fill', concept: 'han_sa_att_han_var_trott', lemma: 'att', source: 'phrase', prompt: { zh: '他说他很累。' }, template: 'Han sa {{att}} han var trött.' },
    { id: 'c4_phrase_de_sa_att_de_skulle_komma', kind: 'phrase_fill', concept: 'de_sa_att_de_skulle_komma', lemma: 'att', source: 'phrase', prompt: { zh: '他们说他们会来。' }, template: 'De sa {{att}} de skulle komma.' },
    { id: 'c4_phrase_han_sa_att_han_hade_gjort_det', kind: 'phrase_fill', concept: 'han_sa_att_han_hade_gjort_det', lemma: 'att', source: 'phrase', prompt: { zh: '他说他已经做完了。' }, template: 'Han sa {{att}} han hade gjort det.' },
    { id: 'c4_phrase_hon_fragade_om_jag_kunde_hjalpa', kind: 'phrase_fill', concept: 'hon_fragade_om_jag_kunde_hjalpa', lemma: 'om', source: 'phrase', prompt: { zh: '她问我能不能帮忙。' }, template: 'Hon frågade {{om}} jag kunde hjälpa.' },
    { id: 'c4_phrase_jag_undrar_om_det_finns_en_tid_pa_fredag', kind: 'phrase_fill', concept: 'jag_undrar_om_det_finns_en_tid_pa_fredag', lemma: 'om', source: 'phrase', prompt: { zh: '我想知道周五是否有时间。' }, template: 'Jag undrar {{om}} det finns en tid på fredag.' },
    { id: 'c4_phrase_ar_blir_var', kind: 'phrase_fill', concept: 'ar_blir_var', lemma: 'var', source: 'phrase', prompt: { zh: '是 → 曾是' }, template: 'är → {{var}}' },
    { id: 'c4_phrase_kan_blir_kunde', kind: 'phrase_fill', concept: 'kan_blir_kunde', lemma: 'kunde', source: 'phrase', prompt: { zh: '能 → 过去能' }, template: 'kan → {{kunde}}' },
    { id: 'c4_phrase_ska_blir_skulle', kind: 'phrase_fill', concept: 'ska_blir_skulle', lemma: 'skulle', source: 'phrase', prompt: { zh: '将要 → 会 / 会去做' }, template: 'ska → {{skulle}}' },
    { id: 'c4_phrase_har_blir_hade', kind: 'phrase_fill', concept: 'har_blir_hade', lemma: 'hade', source: 'phrase', prompt: { zh: '已经有 / 做过' }, template: 'har → {{hade}}' },
    { id: 'c4_phrase_jag_skulle_vilja_boka_en_tid', kind: 'phrase_fill', concept: 'jag_skulle_vilja_boka_en_tid', lemma: 'skulle vilja boka', source: 'phrase', prompt: { zh: '我想预约一个医生时间。' }, template: 'Jag {{skulle vilja boka}} en tid hos läkaren.' },
    { id: 'c4_phrase_har_du_mojlighet_att_komma', kind: 'phrase_fill', concept: 'har_du_mojlighet_att_komma', lemma: 'Har du möjlighet att', source: 'phrase', prompt: { zh: '你周四十点有没有可能过来？' }, template: '{{Har du möjlighet att}} komma på torsdag klockan tio?' },
    { id: 'c4_phrase_jag_undrar_om_det_finns_en_tid', kind: 'phrase_fill', concept: 'jag_undrar_om_det_finns_en_tid', lemma: 'Jag undrar om', source: 'phrase', prompt: { zh: '我想知道周五是否有时间。' }, template: '{{Jag undrar om}} det finns en tid på fredag?' },
    { id: 'c4_phrase_jag_skulle_vilja_framfora_ett_klagomal', kind: 'phrase_fill', concept: 'jag_skulle_vilja_framfora_ett_klagomal', lemma: 'skulle vilja framföra', source: 'phrase', prompt: { zh: '我想提出一个投诉。' }, template: 'Jag {{skulle vilja framföra}} ett klagomål.' },
    { id: 'c4_phrase_skulle_du_kunna_ge_mig_ditt_ordernummer', kind: 'phrase_fill', concept: 'skulle_du_kunna_ge_mig_ditt_ordernummer', lemma: 'Skulle du kunna', source: 'phrase', prompt: { zh: '您能否告诉我订单号？' }, template: '{{Skulle du kunna}} ge mig ditt ordernummer?' },
    { id: 'c4_phrase_det_skulle_vara_bra', kind: 'phrase_fill', concept: 'det_skulle_vara_bra', lemma: 'Det skulle vara bra', source: 'phrase', prompt: { zh: '如果能这样就好了。' }, template: '{{Det skulle vara bra}}.' },
    { id: 'c4_phrase_det_haller_jag_med_om', kind: 'phrase_fill', concept: 'det_haller_jag_med_om', lemma: 'med om', source: 'phrase', prompt: { zh: '是的，我同意这一点。' }, template: 'Ja, det håller jag {{med om}}.' },
    { id: 'c4_phrase_det_stammer', kind: 'phrase_fill', concept: 'det_stammer', lemma: 'stämmer', source: 'phrase', prompt: { zh: '没错。' }, template: 'Det {{stämmer}}.' },
    { id: 'c4_phrase_jag_haller_inte_med', kind: 'phrase_fill', concept: 'jag_haller_inte_med', lemma: 'inte med', source: 'phrase', prompt: { zh: '不，我不同意。' }, template: 'Jag håller {{inte med}}.' },
    { id: 'c4_phrase_det_ar_inte_riktigt_sa', kind: 'phrase_fill', concept: 'det_ar_inte_riktigt_sa', lemma: 'inte riktigt så', source: 'phrase', prompt: { zh: '不完全是这样。' }, template: 'Det är {{inte riktigt så}}.' },
    // ===== 对话句题 =====
    { id: 'c4_dialog_hej_jag_skulle_vilja_boka_en_tid', kind: 'dialog_fill', concept: 'hej_jag_skulle_vilja_boka_en_tid', lemma: 'skulle vilja boka', source: 'dialog', prompt: { zh: '你好，我想预约一个医生时间。' }, template: 'Hej, jag {{skulle vilja boka}} en tid hos läkaren.' },
    { id: 'c4_dialog_har_du_mojlighet_att_komma_pa_torsdag', kind: 'dialog_fill', concept: 'har_du_mojlighet_att_komma_pa_torsdag', lemma: 'Har du möjlighet att', source: 'dialog', prompt: { zh: '你周四十点有没有可能过来？' }, template: '{{Har du möjlighet att}} komma på torsdag klockan tio?' },
    { id: 'c4_dialog_jag_undrar_om_det_finns_en_tid_pa_fredag_dialog', kind: 'dialog_fill', concept: 'jag_undrar_om_det_finns_en_tid_pa_fredag_dialog', lemma: 'Jag undrar om', source: 'dialog', prompt: { zh: '那天不行，我想知道周五是否有时间。' }, template: 'Jag undrar {{om}} det finns en tid på fredag?' },
    { id: 'c4_dialog_jag_skickar_en_bekraftelse_till_dig', kind: 'dialog_fill', concept: 'jag_skickar_en_bekraftelse_till_dig', lemma: 'bekräftelse', source: 'dialog', prompt: { zh: '我会发一个确认给你。' }, template: 'Jag skickar en {{bekräftelse}} till dig.' },
    { id: 'c4_dialog_forlat_jag_skulle_vilja_framfora_ett_klagomal', kind: 'dialog_fill', concept: 'forlat_jag_skulle_vilja_framfora_ett_klagomal', lemma: 'skulle vilja framföra', source: 'dialog', prompt: { zh: '不好意思，我想提出一个投诉。' }, template: 'Förlåt, jag {{skulle vilja framföra}} ett klagomål.' },
    { id: 'c4_dialog_skulle_du_kunna_ge_mig_ditt_ordernummer_dialog', kind: 'dialog_fill', concept: 'skulle_du_kunna_ge_mig_ditt_ordernummer_dialog', lemma: 'Skulle du kunna', source: 'dialog', prompt: { zh: '能否请您给我订单号？' }, template: '{{Skulle du kunna}} ge mig ditt ordernummer?' },
    { id: 'c4_dialog_jag_ska_undersoka_det_och_meddela_dig', kind: 'dialog_fill', concept: 'jag_ska_undersoka_det_och_meddela_dig', lemma: 'meddela', source: 'dialog', prompt: { zh: '我会立即调查，并在一天内通知您。' }, template: 'Jag ska undersöka det direkt och {{meddela}} dig inom en dag.' },
    { id: 'c4_dialog_det_skulle_vara_bra_tack', kind: 'dialog_fill', concept: 'det_skulle_vara_bra_tack', lemma: 'Det skulle vara bra', source: 'dialog', prompt: { zh: '那就太好了，谢谢。' }, template: '{{Det skulle vara bra}}, tack.' }
  ],
  advancedPool: [
    // ===== verb_forms =====
    { id: 'c4_verb_be_om_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'be om', prompt: { zh: '请求' }, template: '{{be om}} | {{ber om}} | {{bad om}} | {{bett om}}' },
    { id: 'c4_verb_erbjuda_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'erbjuda', prompt: { zh: '提供 / 邀请' }, template: '{{erbjuda}} | {{erbjuder}} | {{erbjöd}} | {{erbjudit}}' },
    { id: 'c4_verb_tacka_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'tacka', prompt: { zh: '感谢' }, template: '{{tacka}} | {{tackar}} | {{tackade}} | {{tackat}}' },
    { id: 'c4_verb_avboka_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'avboka', prompt: { zh: '取消预约' }, template: '{{avboka}} | {{avbokar}} | {{avbokade}} | {{avbokat}}' },
    { id: 'c4_verb_boka_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'boka', prompt: { zh: '预约 / 预订' }, template: '{{boka}} | {{bokar}} | {{bokade}} | {{bokat}}' },
    { id: 'c4_verb_klaga_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'klaga', prompt: { zh: '投诉 / 抱怨' }, template: '{{klaga}} | {{klagar}} | {{klagade}} | {{klagat}}' },
    { id: 'c4_verb_paminna_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'påminna', prompt: { zh: '提醒' }, template: '{{påminna}} | {{påminner}} | {{påminde}} | {{påmint}}' },
    { id: 'c4_verb_meddela_group', kind: 'morphology', source: 'verb_forms', labelScheme: 'verb_forms', slotLabels: ['原形', '现在时', '过去时', '完成时'], lemma: 'meddela', prompt: { zh: '通知 / 告知' }, template: '{{meddela}} | {{meddelar}} | {{meddelade}} | {{meddelat}}' },
    // ===== noun_forms =====
    { id: 'c4_noun_arende_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'ärende', prompt: { zh: '事务 / 来意' }, template: '{{ett}} | {{ärende}} | {{ärendet}} | {{ärenden}} | {{ärendena}}' },
    { id: 'c4_noun_klagomal_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'klagomål', prompt: { zh: '投诉' }, template: '{{ett}} | {{klagomål}} | {{klagomålet}} | {{klagomål}} | {{klagomålen}}' },
    { id: 'c4_noun_bokning_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'bokning', prompt: { zh: '预订' }, template: '{{en}} | {{bokning}} | {{bokningen}} | {{bokningar}} | {{bokningarna}}' },
    { id: 'c4_noun_bekraftelse_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'bekräftelse', prompt: { zh: '确认 / 回执' }, template: '{{en}} | {{bekräftelse}} | {{bekräftelsen}} | {{bekräftelser}} | {{bekräftelserna}}' },
    { id: 'c4_noun_tidbokning_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'tidbokning', prompt: { zh: '预约时间' }, template: '{{en}} | {{tidbokning}} | {{tidbokningen}} | {{tidbokningar}} | {{tidbokningarna}}' },
    { id: 'c4_noun_vantetid_group', kind: 'morphology', source: 'noun_forms', labelScheme: 'noun_forms', lemma: 'väntetid', prompt: { zh: '等待时间' }, template: '{{en}} | {{väntetid}} | {{väntetiden}} | {{väntetider}} | {{väntetiderna}}' },
    // ===== politeness pattern =====
    { id: 'c4_polite_skulle_du_kunna_hjalpa_mig', kind: 'morphology', source: 'pattern', lemma: 'Skulle du kunna hjälpa mig', prompt: { zh: '礼貌表达' }, template: '{{Skulle du kunna}} hjälpa mig?' },
    { id: 'c4_polite_har_du_mojlighet_att_komma', kind: 'morphology', source: 'pattern', lemma: 'Har du möjlighet att komma på torsdag', prompt: { zh: '礼貌表达' }, template: '{{Har du möjlighet att}} komma på torsdag?' },
    { id: 'c4_polite_jag_undrar_om_det_finns_en_tid', kind: 'morphology', source: 'pattern', lemma: 'Jag undrar om det finns en tid på fredag', prompt: { zh: '礼貌表达' }, template: '{{Jag undrar om}} det finns en tid på fredag.' },
    { id: 'c4_polite_det_skulle_vara_bra_om', kind: 'morphology', source: 'pattern', lemma: 'Det skulle vara bra om', prompt: { zh: '礼貌表达' }, template: '{{Det skulle vara bra om}} ...' },
    { id: 'c4_polite_skulle_vilja_boka', kind: 'morphology', source: 'pattern', lemma: 'skulle vilja boka', prompt: { zh: '礼貌表达' }, template: '{{skulle vilja boka}}' },
    { id: 'c4_polite_skulle_vilja_framfora', kind: 'morphology', source: 'pattern', lemma: 'skulle vilja framföra ett klagomål', prompt: { zh: '礼貌表达' }, template: '{{skulle vilja framföra}} ett klagomål' }
  ]
};
